Add shared-modules section to handbook->javascript
theforeman/theforeman.org pull request #1023
Opened 2018-02-22 09:49 UTC by sharvit

Add documentation about shared node-modules and the `config/webpack.vendor.js`

2018-02-23 15:07 UTC, dLobatog requested changes
Great addition, thanks @sharvit

2018-02-23 15:07 UTC, dLobatog commented on handbook.md
> +Usually, when we add a new node-module, we want it to be shared with plugins (Unless we have a reason not share it).
`a reason not to share it`

2018-02-23 15:07 UTC, dLobatog commented on handbook.md
> +In order to do so, we let [webpack](https://webpack.js.org/) to create a `vendor.js` file with the relevant modules.
`we let webpack create`

2018-02-25 06:57 UTC, sharvit commented
Thanks @dLobatog, updated!

2018-02-28 08:09 UTC, dLobatog approved these changes
Merging! :medal_military: @sharvit

2018-02-28 08:09 UTC, merged