Add 3.5 API documentation
theforeman/theforeman.org pull request #1035
Opened 2018-03-05 03:11 UTC by akofink

2018-03-05 14:45 UTC, stbenjam requested changes
index.md still says docs aren't generated when I load up the site locally. 

It looks like everything is in apipie-cache dir, which doesn't look like the same dir structure as 3.4.

2018-03-05 20:04 UTC, akofink commented
Ok, it should work now. Thanks for testing. :)

2018-03-07 14:49 UTC, stbenjam approved these changes

2018-03-07 14:49 UTC, stbenjam commented
Tested & works, thanks @akofink

2018-03-07 14:49 UTC, merged