SUSE SMT Documentation
theforeman/theforeman.org pull request #1056
Opened 2018-04-10 22:56 UTC by parthaa

This commit adds docs to mirror content from SUSE SCC via the SMT tool.

2018-04-11 14:30 UTC, johnpmitsch commented
formatting looks off

![f](http://www.clipular.com/c/5970407396737024.png?k=MqoH9QN7J1zdZW1O1arJ-Bzvboc)

2018-04-17 21:07 UTC, parthaa commented
@johnpmitsch updated

2018-04-17 21:55 UTC, sean797 commented
Do we need to have anything for registering and updating client SUSE systems?

2018-04-18 09:28 UTC, tbrisker commented on _includes/plugins/katello/sidebar_nightly.html
> +        5.17 SUSE Content
Shouldn't this be 5.18?

2018-04-18 10:50 UTC, bbuckingham commented
@sean797, we have a separate task to cover clients.  That should be coming soon as well.  :)

2018-04-18 19:25 UTC, johnpmitsch requested changes
Some small changes, but otherwise looks good!

2018-04-18 19:25 UTC, johnpmitsch commented on plugins/katello/nightly/user_guide/suse_content/index.md
> +- Follow the steps listed [here](/plugins/katello/{{ page.version }}/user_guide/content/index.html) to Create Products and repositories
This goes to the same link as below, I don't think we really need this bullet point and can just keep the second one

2018-04-18 19:25 UTC, johnpmitsch commented on plugins/katello/nightly/user_guide/suse_content/index.md
> +- Follow the steps listed [here](/plugins/katello/{{ page.version }}/user_guide/content/index.html) to Create a yum repository with the repository url pointing to the appropriate location. For exampl
s/Create/create/

2018-04-20 04:04 UTC, parthaa commented
@johnpmitsch updated

2018-04-20 19:55 UTC, johnpmitsch commented on plugins/katello/nightly/user_guide/suse_content/index.md
> +- Follow the steps listed [here](/plugins/katello/{{ page.version }}/user_guide/content/index.html) to Create Products and Repositories
this still needs s/Create/create

2018-04-23 19:28 UTC, johnpmitsch approved these changes

2018-04-23 19:29 UTC, merged

2018-04-23 19:29 UTC, johnpmitsch commented
thanks @parthaa!