Explained how to delete old & anonymize audit records
theforeman/theforeman.org pull request #1059
Opened 2018-04-17 12:32 UTC by kgaikwad

2018-04-17 12:45 UTC, ares requested changes
few nits in text, otherwise :+1:

2018-04-17 12:45 UTC, ares commented on _includes/manuals/1.18/4.1.4_auditing.md
> +
double empty line

2018-04-17 12:45 UTC, ares commented on _includes/manuals/1.18/4.1.4_auditing.md
> +
double empty line

2018-04-17 12:45 UTC, ares commented on _includes/manuals/1.18/4.1.4_auditing.md
> +Available conditions:
s/conditions/parameters/

2018-04-17 12:45 UTC, ares commented on _includes/manuals/1.18/4.1.4_auditing.md
> +You can anonymize your old audits instead of deleting the audit entries.
I'd also add a sentence like "Anonymization clears links to user accounts and their IP addresses, but keeps all changes other audit data in database"

2018-04-17 13:04 UTC, kgaikwad commented
@ares,
Thank you for reviewing pull-request. I have updated the pull-request.

2018-04-18 06:01 UTC, ares approved these changes

2018-04-18 06:02 UTC, ares commented
Content wise :+1: it would be good if someone could do the grammar check, but then it's good to go in. Thanks @kgaikwad

2018-04-18 09:25 UTC, tbrisker approved these changes
LGTM, Thanks @kgaikwad and @ares !

2018-04-18 09:25 UTC, merged