Update katello rpm signing docs
theforeman/theforeman.org pull request #1147
Opened 2018-07-24 18:13 UTC by jlsherrill

2018-07-25 16:32 UTC, ehelms commented
Thanks for the updates. If we were going to automate this in the future would you see this as a tool_belt command or obal functionality?

2018-07-25 16:35 UTC, ekohl commented
Something like tool_belt would make sense to me because the Foreman process is *very* similar, just with different tags/versions.

2018-07-25 18:41 UTC, jlsherrill commented
yep +1 to toolbelt

2018-08-13 12:42 UTC, ekohl requested changes

2018-08-13 12:42 UTC, ekohl commented on plugins/katello/developers.md
> +gpg --improt katello.private.asc
improt -> import

2019-01-09 16:48 UTC, jlsherrill commented
Closing, as i do have a script that i want to adapt to toolbelt

2019-01-09 16:48 UTC, closed without merging