Remove deprecated email.yml setting file
theforeman/theforeman.org pull request #1153
Opened 2018-07-26 13:44 UTC by tbrisker

2018-07-26 14:16 UTC, ekohl requested changes

2018-07-26 14:16 UTC, ekohl commented on _includes/manuals/1.16/3.5.2_configuration_options.md
> +**This file has been deprecated for configuring email, SMTP and sendmail options. Please remove it and configure via the web UI under *Administer > Settings > Email* instead. On Foreman 1.16 or later
I think this should be in the Upgrade guide and release notes. The reference manual shouldn't document the outdated section.

2018-07-26 15:55 UTC, tbrisker commented
i started digging a bit deeper and found other references to email.yaml that led me to discover we still support file based email config in the installer.... opened https://projects.theforeman.org/issues/24399 to track that.
I'm out for the weekend, i'll continue with removing this from the manual next week.

2018-07-26 16:13 UTC, ekohl commented
Thanks! https://github.com/theforeman/puppet-foreman/pull/656 should take care of that. Now we're getting back in the regular releasing and cleaning up.

2018-07-29 16:56 UTC, tbrisker commented
I hope I got all of them now.

2018-08-13 12:40 UTC, ekohl approved these changes

2018-08-13 14:17 UTC, merged