Update 1.19 and nightly manual
theforeman/theforeman.org pull request #1165
Opened 2018-08-02 13:55 UTC by tbrisker

@ekohl - I think this should include all of the remaining comments from your review.

2018-08-02 14:01 UTC, ekohl requested changes

2018-08-02 14:01 UTC, ekohl commented on _includes/manuals/1.19/3.6_upgrade.md
>  tfm-ror51 repositories:
tfm-ror51 will no longer come from this repo since https://github.com/theforeman/foreman-packaging/commit/fc8687eb98f932d7ef1576d1a0ed93489bc17680

2018-08-02 14:01 UTC, ekohl commented on _includes/manuals/1.19/3.6_upgrade.md
>  First upgrade or install the SCL release package to add rh-ruby24 and
This only upgrades. If the package is not yet installed then it'll do nothing:
```
[root@bd55df735b49 /]# yum upgrade foreman-release-scl
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirror.karneval.cz
 * extras: mirror.karneval.cz
 * updates: mirror.karneval.cz
Package(s) foreman-release-scl available, but not installed.
No packages marked for update
```

2018-08-02 14:01 UTC, ekohl commented on _includes/manuals/nightly/3.6_upgrade.md
>  First upgrade or install the SCL release package to add rh-ruby24 and
Same comments as in 1.19

2018-08-13 07:56 UTC, tbrisker commented on _includes/manuals/1.19/3.6_upgrade.md
>  tfm-ror51 repositories:
So should this step be completely removed?

2018-08-13 08:51 UTC, ekohl commented on _includes/manuals/1.19/3.6_upgrade.md
>  tfm-ror51 repositories:
No, we still use `foreman-release-scl` to pull in `centos-release-scl` and `centos-release-scl-rh` (though we only need the latter I think) so it's still needed. We used to depend on `centos-release-scl` for `sclo-ror42` but we now host our own rails SCL.

2018-08-13 12:34 UTC, tbrisker commented
@ekohl addressed your comment

2018-08-21 07:17 UTC, tbrisker commented
ping @ekohl ?

2018-08-21 10:41 UTC, ekohl approved these changes
We probably need to go over all `/var/lib/puppet/ssl` paths but IMHO this good to go now.

2018-08-21 10:41 UTC, merged