Updates for 1.17.1 and 1.17.3
theforeman/theforeman.org pull request #1179
Opened 2018-08-23 10:27 UTC by xprazak2

2018-08-23 11:19 UTC, ekohl requested changes

2018-08-23 11:19 UTC, ekohl commented on _includes/manuals/1.17/1.2_release_notes.md
> +### Release notes for 1.17.3 (1.17.2 was not released due to packaging issues)
I wouldn't say it was a packaging issue, it was a critical regression in VMware provisioning.

2018-08-24 12:32 UTC, xprazak2 commented
I changed the explanation why 1.17.2 was not released.

2018-08-24 12:39 UTC, ekohl commented
I am wondering if Release notes 1.17.2 should be a separate section where the description is the body. I think that'll create a more usable table of contents. Other than that :+1:

2018-08-26 14:19 UTC, tbrisker commented
Can you please include https://projects.theforeman.org/issues/24697 and https://projects.theforeman.org/issues/24640 in the upgrade warnings section?

2018-08-29 12:14 UTC, tbrisker approved these changes
Thanks @xprazak2

2018-08-29 12:14 UTC, merged