Switch to using Foreman client repository for Katello
theforeman/theforeman.org pull request #1201
Opened 2018-10-04 12:52 UTC by ehelms

2018-10-05 14:54 UTC, jturel commented
LGTM @ehelms. Have the new client repos been tested at all?

2018-10-05 15:49 UTC, ekohl requested changes

2018-10-05 15:49 UTC, ekohl commented on plugins/katello/nightly/installation/clients.md
> +yum install -y http://yum.theforeman.org/client/{{ page.foreman_version }}/el5/x86_64/foreman-client-release.rpm
We do have https available and for release RPMs that's strongly preferred IMHO

2018-10-07 07:49 UTC, ik5 commented on plugins/katello/nightly/installation/clients.md
> +yum install -y http://yum.theforeman.org/client/{{ page.foreman_version }}/el6/x86_64/foreman-client-release.rpm
what does `page.foreman_version` holds? I went to the path and there is only `nightly` there.

and as @ekohl wrote, please prefer `https` ;)

2018-10-08 21:27 UTC, ehelms commented on plugins/katello/nightly/installation/clients.md
> +yum install -y http://yum.theforeman.org/client/{{ page.foreman_version }}/el6/x86_64/foreman-client-release.rpm
The page template defines `page.foreman_version` depending on the matchup of releases. So for Katello nightly this value is nightly

2018-10-09 00:52 UTC, ehelms commented
Updated to https

2018-10-09 17:49 UTC, jturel commented
I tested the client repos for el7 and f27 - all packages installed and behave correctly. ACK from me

2018-10-09 17:49 UTC, jturel approved these changes

2018-10-10 12:30 UTC, ekohl approved these changes

2018-10-10 12:33 UTC, merged