Update installation instructions for foreman_ansible
theforeman/theforeman.org pull request #1229
Opened 2018-11-13 13:19 UTC by xprazak2

I think the installer should be used rather than installing the packages. @dLobatog, does this seem ok to you?

2018-11-13 13:46 UTC, ekohl requested changes

2018-11-13 13:46 UTC, ekohl commented on plugins/foreman_ansible/2.x/index.md
> +Restarting Foreman might be needed after installing the package. To run Asnible playbooks as Job Templates, you will also need Remote Execution:
Asnible -> Ansible. The yum package should also restart the foreman application. If not, I think that's a bug.

2018-11-14 07:05 UTC, xprazak2 commented
I fixed the typo and removed the hint to restart Foreman.

2018-11-17 11:47 UTC, ekohl approved these changes

2018-11-17 11:47 UTC, merged