add second version of the katello testing slides
theforeman/theforeman.org pull request #1302
Opened 2019-02-05 16:33 UTC by evgeni

2019-02-06 15:17 UTC, ekohl requested changes
There's a merge conflict now

2019-02-06 15:17 UTC, ekohl commented on _layouts/media.html
> +          <li><a href="/static/presentations/evgeni_golov-katello_and_ansible_for_automated_testing_and_releasing_of_packages.pdf">Katello and Ansible for automated testing and releasing of packages<
Odd indenting

2019-02-08 08:08 UTC, evgeni commented on _layouts/media.html
> +          <li><a href="/static/presentations/evgeni_golov-katello_and_ansible_for_automated_testing_and_releasing_of_packages.pdf">Katello and Ansible for automated testing and releasing of packages<
my vim hates tabs :)

2019-02-08 08:08 UTC, evgeni commented
updated!

2019-02-08 10:28 UTC, ekohl approved these changes

2019-02-08 10:28 UTC, merged