Update report templates manuals
theforeman/theforeman.org pull request #1350
Opened 2019-04-15 15:58 UTC by ezr-ondrej

Explaining new features coming in 1.22 for report templates.
Any grammar checks would be helpful, even though I did my best :smile_cat:

2019-04-16 13:46 UTC, tbrisker requested changes
added some grammar corrections, otherwise looks good.

2019-04-16 13:46 UTC, tbrisker commented on _includes/manuals/nightly/4.11.1_report_templates.md
> +In a generating form you can choose a time, for a generating start time. There is
```suggestion
In the report generation form you can choose a starting time for delayed generation. There is
```

2019-04-16 13:46 UTC, tbrisker commented on _includes/manuals/nightly/4.11.1_report_templates.md
> +no way to schedule repeated generating, but as the report generating can be started
```suggestion
no way to schedule repeated generation, but as the report generating can be started
```

2019-04-16 13:46 UTC, tbrisker commented on _includes/manuals/nightly/4.11.1_report_templates.md
> +by a *hammer report-template* command, the scheduling can be achieved from cron.
```suggestion
by a *hammer report-template* command, scheduling can be achieved using cron.
```

2019-04-16 13:46 UTC, tbrisker commented on _includes/manuals/nightly/4.11.1_report_templates.md
> +##### Planing and deliver via e-mail
```suggestion
##### Scheduling and delivering reports via e-mail
```

2019-04-16 13:46 UTC, tbrisker commented on _includes/manuals/nightly/4.11.1_report_templates.md
> +For this planned repots, as well as for long running reports it is no longer useful
```suggestion
For these planned reports, as well as for long running reports, it is no longer useful
```

2019-04-16 13:46 UTC, tbrisker commented on _includes/manuals/nightly/4.11.1_report_templates.md
> +to have the report downloaded by web browser. In such cases you can choose to get
```suggestion
to have the report downloaded by the web browser. In such cases you can choose to get
```

2019-04-16 13:46 UTC, tbrisker commented on _includes/manuals/nightly/4.11.1_report_templates.md
> +the report delivered via e-mail by simply checking a *Send report via e-mail* and
```suggestion
the report delivered via e-mail by simply checking *Send report via e-mail* and
```

2019-04-17 22:21 UTC, ezr-ondrej commented on _includes/manuals/nightly/4.11.1_report_templates.md
> +In a generating form you can choose a time, for a generating start time. There is
This I have rewritten a bit.

2019-04-17 22:23 UTC, ezr-ondrej commented
I am trying to avoid the `generation` as it is misleading, see https://www.merriam-webster.com/dictionary/generation where it stated that first association is with
> a body of living beings constituting a single step in the line of descent from an ancestor
what we do not want to state.

2019-04-18 09:27 UTC, tbrisker approved these changes
Thanks @ezr-ondrej !

2019-04-18 09:27 UTC, merged