Remove warnings, deprecation from 1.23 manual
theforeman/theforeman.org pull request #1422
Opened 2019-07-24 13:12 UTC by upadhyeammit

Removed deprecation and warnings from 1.23 manual.

2019-07-24 13:12 UTC, upadhyeammit commented
@tbrisker request to check. Thank You !

2019-07-24 13:17 UTC, tbrisker commented
@upadhyeammit sorry, i may have not explained myself clearly, these should be removed from nightly manual, not 1.23.

2019-07-24 15:20 UTC, upadhyeammit commented
@tbrisker pushed the changes, request to check. Thank You !

2019-07-25 07:27 UTC, tbrisker requested changes

2019-07-25 07:27 UTC, tbrisker commented on _includes/manuals/nightly/1.2_release_notes.md
> -### Deprecations
Please keep the section headers

2019-07-25 07:27 UTC, tbrisker commented on _includes/manuals/nightly/1.2_release_notes.md
> -### Upgrade warnings
this one too

2019-07-25 07:46 UTC, tbrisker approved these changes
Thanks @upadhyeammit !

2019-07-25 07:47 UTC, merged