Update Puppet documentation
theforeman/theforeman.org pull request #1435
Opened 2019-08-07 20:14 UTC by ekohl

This is incomplete since at least the Puppet CA part needs to document the HTTP API-based implementation that's used since Puppet 6.

2019-08-07 20:15 UTC, ekohl commented on _includes/manuals/nightly/3.3.1_rpm_packages.md
> +* `/client` or `/client/VERSION` (e.g. `/client/{{page.version}}`) carries packages relevant to clients. This is optional and Foreman does not require anything installed on clients.
Not really Puppet related, but needed an update as well.

2019-08-07 20:15 UTC, ekohl commented on _includes/manuals/nightly/3.3.1_rpm_packages.md
> +1. Start the foreman service or set up passenger: `systemctl start foreman`
This needs the foreman-service package to be installed. Will need a larger overhaul.

2019-08-08 09:21 UTC, ekohl commented on _includes/manuals/nightly/3.1.3_puppet_versions.md
> +    <td>4.4-4.10</td>
Technically the Smart Proxy should work with 4.4+ since the API hasn't changed. Do we want to advertise that or just say it's unsupported?

2019-08-11 11:31 UTC, tbrisker reviewed
Looks good in general, happy for all the clean up of old stuff. I do not know if all the path changes are correct but I trust that you do. My main question is regarding support for non-AIO installs - should we still support that? it sounds like it's complicating things quite a lot (different settings and paths everywhere) and we don't actually test that it works. Since we require foreman to be installed on its own server, why not require AIO always even if the user uses non-AIO elsewhere?

2019-08-11 11:31 UTC, tbrisker commented on _includes/manuals/nightly/3.1.3_puppet_versions.md
> +    <td>4.4-4.10</td>
I think deprecated is fine, so we can drop it if needed

2019-08-11 11:31 UTC, tbrisker commented on _includes/manuals/nightly/3.1.3_puppet_versions.md
> +The Foreman installer has code for both AIO and non-AIO configurations, switching behavior automatically based on the version of Puppet installed (usually during the first run when answers are stored
Perhaps we should consider dropping non-AIO compatibility? considering it isn't tested and puppetserver isn't included in non-AIO. Would that simplify the installer as well?

2019-09-12 11:22 UTC, ekohl commented on _includes/manuals/nightly/3.1.3_puppet_versions.md
> +The Foreman installer has code for both AIO and non-AIO configurations, switching behavior automatically based on the version of Puppet installed (usually during the first run when answers are stored
It wouldn't simplify it a lot. We could drop some 15 lines from `params.pp` (https://github.com/theforeman/puppet-puppet/blob/10f437eb86f2dc45a470cc7ae1bdea7e33a2338a/manifests/params.pp#L133-L149) but for selfish reasons I don't want to drop them because it's how I deploy my Puppet agents.

2019-09-12 11:23 UTC, ekohl commented
I've updated 4.3.6_smartproxy_puppet.md and 4.3.7_smartproxy_puppetca.md to fully document the current configs. If this is merged, the same should be applied to 1.23.

2019-09-12 11:43 UTC, tbrisker commented on _includes/manuals/nightly/3.1.3_puppet_versions.md
> +The Foreman installer has code for both AIO and non-AIO configurations, switching behavior automatically based on the version of Puppet installed (usually during the first run when answers are stored
What about removing this option from the manual then and leaving it as an advanced option?

2019-09-12 11:58 UTC, ekohl commented on _includes/manuals/nightly/3.1.3_puppet_versions.md
> +The Foreman installer has code for both AIO and non-AIO configurations, switching behavior automatically based on the version of Puppet installed (usually during the first run when answers are stored
I'd prefer to explicitly mention this rather than wait for questions about this. A lot of admins will assume the system packages and the Debian packages will accept both. That means if they didn't set up the AIO repositories, it'll work. The RPMs only accept the AIO package since there are no up to date non-AIO on EL and we don't package for Fedora.

2019-09-16 11:04 UTC, tbrisker requested changes
Just a couple of small comments, otherwise looks like a great clean up!

2019-09-16 11:04 UTC, tbrisker commented on _includes/manuals/nightly/3.2.3_installation_scenarios.md
> +Under a Puppet AIO installation, substitute above paths with `/etc/puppetlabs/puppet/ssl/`.
Shouldn't the default instructions be for AIO since that's the tested and recommended path and the comment for non-AIO?

2019-09-16 11:04 UTC, tbrisker commented on _includes/manuals/nightly/3.1.3_puppet_versions.md
> +The Foreman installer has code for both AIO and non-AIO configurations, switching behavior automatically based on the version of Puppet installed (usually during the first run when answers are stored
I would prefer to be as opinionated as possible on the installation instructions we provide our users as well as the supported setups, but I won't block on this.

2019-09-16 11:04 UTC, tbrisker commented on _includes/manuals/nightly/3.3.1_rpm_packages.md
> +1. Start the foreman service or set up passenger: `systemctl start foreman`
shouldn't this be `systemctl start httpd` for starting passanger?

2019-09-16 16:07 UTC, ekohl commented on _includes/manuals/nightly/3.2.3_installation_scenarios.md
> +Under a Puppet AIO installation, substitute above paths with `/etc/puppetlabs/puppet/ssl/`.
Good point. In other places I've swapped them and should do the same here.

It also looks like I should update this to make note of Puppet 5 vs Puppet 6 for which the instructions here are outdated.

2019-09-27 18:58 UTC, ekohl commented
I've done a partial update of the deployment scenarios but haven't tested it yet

2019-10-27 12:48 UTC, tbrisker commented
This is already a good improvement. i'm going to merge this now before branching the manual for 1.24 and we can improve as needed afterwards.

2019-10-27 12:48 UTC, merged

2019-10-27 12:48 UTC, tbrisker commented
Thanks @ekohl !