Updates to reflect RC2
theforeman/theforeman.org pull request #1468
Opened 2019-09-20 14:51 UTC by jjeffers

Also mentions use of the Foreman key for package signature.

2019-09-20 15:12 UTC, ekohl requested changes

2019-09-20 15:12 UTC, ekohl commented on plugins/katello/3.13/release_notes/release_notes.md
> +Previous releases were signed using the Katelo key, but starting with 3.13 package signing will use the [Foreman Key](https://theforeman.org/static/keys/4674C97BD8C2A3EF63BCB20788BB5C467B5B366A.pub).
No need to include the domain:
```suggestion
Previous releases were signed using the Katelo key, but starting with 3.13 package signing will use the [Foreman Key](/static/keys/4674C97BD8C2A3EF63BCB20788BB5C467B5B366A.pub).
```

Probably also good to show the fingerprint similar to how we do on https://theforeman.org/security.html

2019-09-20 15:47 UTC, ekohl approved these changes

2019-09-20 15:47 UTC, ekohl commented
Build is still running.

2019-09-23 11:10 UTC, evgeni approved these changes

2019-09-23 11:11 UTC, merged