Updates for 3.13.0.
theforeman/theforeman.org pull request #1475
Opened 2019-10-04 19:37 UTC by jjeffers

2019-10-07 14:45 UTC, evgeni approved these changes

2019-10-07 16:52 UTC, jturel requested changes
The 'latest' metadata should be updated across all the katello versions

2019-10-07 17:02 UTC, jturel commented on plugins/katello/3.12/installation/index.md
> +latest: '3.13:'
extra ':' snuck in

2019-10-07 17:07 UTC, jjeffers commented on plugins/katello/3.12/installation/index.md
> +latest: '3.13:'
:(

2019-10-07 17:21 UTC, jturel approved these changes
LGTM!

2019-10-08 18:42 UTC, evgeni approved these changes

2019-10-08 18:42 UTC, merged