Add CentOS 8 provisioning info
theforeman/theforeman.org pull request #1479
Opened 2019-10-16 18:05 UTC by ianballou

Related bug: https://projects.theforeman.org/issues/27948?issue_count=21&issue_position=9&next_issue_id=28036&prev_issue_id=28029

2019-10-17 16:12 UTC, ianballou commented
Actually let's hold off on this for a bit, deciding if this is the proper fix.

2019-10-17 18:01 UTC, chris1984 requested changes
Thanks @ianballou looks good, just left a few nitpick comments for better syntax highlighting

2019-10-17 18:01 UTC, chris1984 commented on plugins/katello/3.10/user_guide/provisioning/index.md
> +```
can you do "```ruby" so it does syntax highlighting better?

2019-10-17 18:01 UTC, chris1984 commented on plugins/katello/3.10/user_guide/provisioning/index.md
> +```
can you do "```ruby" so it does syntax highlighting better?

2019-10-17 18:01 UTC, chris1984 commented on plugins/katello/3.11/user_guide/provisioning/index.md
> +```
can you do "```ruby" so it does syntax highlighting better?

2019-10-17 18:01 UTC, chris1984 commented on plugins/katello/3.11/user_guide/provisioning/index.md
> +```
can you do "```ruby" so it does syntax highlighting better?

2019-10-17 18:01 UTC, chris1984 commented on plugins/katello/3.12/user_guide/provisioning/index.md
> +```
can you do "```ruby" so it does syntax highlighting better?

2019-10-17 18:01 UTC, chris1984 commented on plugins/katello/3.12/user_guide/provisioning/index.md
> +```
can you do "```ruby" so it does syntax highlighting better?

2019-10-17 18:01 UTC, chris1984 commented on plugins/katello/nightly/user_guide/provisioning/index.md
> +```
can you do "```ruby" so it does syntax highlighting better?

2019-10-17 18:01 UTC, chris1984 commented on plugins/katello/nightly/user_guide/provisioning/index.md
> +```
can you do "```ruby" so it does syntax highlighting better?

2019-10-17 18:01 UTC, chris1984 commented on plugins/katello/3.13/user_guide/provisioning/index.md
> +```
can you do "```ruby" so it does syntax highlighting better?

2019-10-17 18:01 UTC, chris1984 commented on plugins/katello/3.13/user_guide/provisioning/index.md
> +```
can you do "```ruby" so it does syntax highlighting better?

2019-10-17 18:07 UTC, chris1984 approved these changes
ACK thanks @ianballou

2019-10-17 18:08 UTC, ianballou commented
@chris1984 I've updated it with ```erb since I'm just talking about provisioning templates.

2019-10-22 13:40 UTC, johnpmitsch commented on plugins/katello/3.11/user_guide/provisioning/index.md
> +**Note:** Currently, CentOS 8 Anaconda requires that the AppStream repository is specifically named "AppStream".  To get around this, edit the Kickstart default provisioning template (or create a new
if there is an open centos8 issue for this, it would be nice to link here so people can quickly tell if this is still relevant

2019-10-22 13:40 UTC, johnpmitsch commented on plugins/katello/3.11/user_guide/provisioning/index.md
> +**Note:** Currently, CentOS 8 Anaconda requires that the AppStream repository is specifically named "AppStream".  To get around this, edit the Kickstart default provisioning template (or create a new
(obviously, this goes for all versions updated)

2019-10-22 14:27 UTC, ianballou commented on plugins/katello/3.11/user_guide/provisioning/index.md
> +**Note:** Currently, CentOS 8 Anaconda requires that the AppStream repository is specifically named "AppStream".  To get around this, edit the Kickstart default provisioning template (or create a new
Sounds good, I've updated them with the bug link.

2019-10-22 14:33 UTC, johnpmitsch approved these changes
Thanks @ianballou!

2019-10-22 14:34 UTC, merged