Update openscap docs for 1.0
theforeman/theforeman.org pull request #1491
Opened 2019-11-05 07:43 UTC by xprazak2

2019-11-05 13:19 UTC, tbrisker commented on plugins/foreman_openscap/1.0/index.md
> +# uncomment for older versions than stable or nightly
These need updating

2019-11-07 13:01 UTC, xprazak2 commented
Updated

2019-11-18 12:48 UTC, tbrisker requested changes
There's a bunch of places linking to wrong manual versions, i hope i found all of them. 
@ares can you also take a look from the functionality pov? i'm not really up to date with all recent changes in the plugin to make sure they are all covered in the manual

2019-11-18 12:48 UTC, tbrisker commented on plugins/foreman_openscap/1.0/index.md
> +#robots: noindex
You should probably uncomment this for the older versions

2019-11-18 12:48 UTC, tbrisker commented on plugins/foreman_openscap/1.0/index.md
> +<table class="table table-bordered table-condensed">
This probably needs to be updated as well, i don't think anyone cares about 0.3.4 being compatible with foreman 1.7 when they read the manual for 1.0 version of the plugin

2019-11-18 12:48 UTC, tbrisker commented on plugins/foreman_openscap/1.0/index.md
> +Manual policy deployment does not require to install anything, but leaves configuration to user. See section [4.6.2](plugins/foreman_openscap/0.9/index.html#4.6.2Manualpolicydeployments) for details.
```suggestion
Manual policy deployment does not require to install anything, but leaves configuration to user. See section [4.6.2](plugins/foreman_openscap/{{page.version_short}}/index.html#4.6.2Manualpolicydeployments) for details.
```

2019-11-18 12:48 UTC, tbrisker commented on plugins/foreman_openscap/1.0/index.md
> +Please read [section](plugins/foreman_openscap/0.9/index.html#4.6.1Authenticatingclients) about client authentication if running Foreman without Katello. Recommended way is to install the packaged ve
```suggestion
Please read [section](plugins/foreman_openscap/{{page.version_short}}/index.html#4.6.1Authenticatingclients) about client authentication if running Foreman without Katello. Recommended way is to install the packaged version from our repositories:
```

2019-11-18 12:48 UTC, tbrisker commented on plugins/foreman_openscap/1.0/index.md
> +version_short: 1.0
This needs to be quoted so it's not interpreted as float

2019-11-18 12:48 UTC, tbrisker commented on plugins/foreman_openscap/1.0/index.md
> +* Deployment Options - how the client will be deployed. The options are Ansible (provided you have foreman_ansible plugin), Puppet or manual. It is recommended to use Puppet or Ansible for client dep
```suggestion
* Deployment Options - how the client will be deployed. The options are Ansible (provided you have foreman_ansible plugin), Puppet or manual. It is recommended to use Puppet or Ansible for client deployment as they provide a convenient way of applying changes. See section [2.3](plugins/foreman_openscap/{{page.version_short}}/index.html#2.3Policydeploymentoptions) for details on policy deployment options.
```

2019-11-18 12:48 UTC, tbrisker commented on plugins/foreman_openscap/1.0/index.md
> +    ---
I think you can use ```yaml to have syntax highlighting here

2019-11-18 12:48 UTC, tbrisker commented on plugins/foreman_openscap/1.0/index.md
> +Then [import](plugins/foreman_ansible/2.x/index.html#4.1.1ImportingRoles) the role into Foreman.
should this point to ansible 3.x?

2019-11-18 12:48 UTC, tbrisker commented on plugins/foreman_openscap/1.0/index.md
> +## 3.1 Migrating ARF reports from 0.4.x
Is this section still relevant?

2019-11-18 12:48 UTC, tbrisker commented on plugins/foreman_openscap/1.0/index.md
> +
we are on version 1.x, so it doesn't matter what was used before, just what is needed now.

2019-11-18 12:48 UTC, tbrisker commented on plugins/foreman_openscap/1.0/index.md
> +## 4.5 Tailoring files ( foreman_openscap >= 0.6.5 )
```suggestion
## 4.5 Tailoring files
```

2019-11-18 12:48 UTC, tbrisker commented on plugins/foreman_openscap/1.0/index.md
> +* foreman_scap_client Puppet module or Ansible role - it will take care of configuring the host with foreman_scap_client. Note that while puppet runs are scheduled periodically, you need to apply Ans
ansible version again - maybe use another page variable to make sure we link the correct version everywhere?

2019-11-18 12:48 UTC, tbrisker commented on plugins/foreman_openscap/1.0/index.md
> +2) Create client config in /etc/foreman_scap_client/config.yaml and populate it with appropriate values. See example config in section [6.3](plugins/foreman_openscap/0.9/index.html#6.3Configforclient
```suggestion
2) Create client config in /etc/foreman_scap_client/config.yaml and populate it with appropriate values. See example config in section [6.3](plugins/foreman_openscap/{{page.version_short}}/index.html#6.3Configforclient). The most convenient way to get the attributes for policies is to add a host parameter with `<%= @host.policies_enc %>` value to your client and then get the JSON value it generates from ENC.
```

2019-11-18 12:48 UTC, tbrisker commented on plugins/foreman_openscap/1.0/index.md
> +3) Make sure client has access to certificates to authenticate (See [previous](plugins/foreman_openscap/0.9/index.html#4.6.1Authenticatingclients) section for details).
```suggestion
3) Make sure client has access to certificates to authenticate (See [previous](plugins/foreman_openscap/{{page.version_short}}/index.html#4.6.1Authenticatingclients) section for details).
```

2019-11-18 12:48 UTC, tbrisker commented on plugins/foreman_openscap/1.0/index.md
> +## 4.7 Running a scan from UI ( foreman_openscap >= 0.6.5 )
```suggestion
## 4.7 Running a scan from UI
```

2019-11-18 12:48 UTC, tbrisker commented on plugins/foreman_openscap/1.0/index.md
> +In version 0.6.5 and higher, you can initiate scans from UI. Simply go to hosts page and select "Run OpenSCAP scan" from the dropdown menu. This will initiate a scan for all policies that are assigne
This could probably be re-worded to get rid of the history part.

2019-11-18 12:48 UTC, tbrisker commented on plugins/foreman_openscap/1.0/index.md
> +## 6.5 Slow queries due to many message records in database ( foreman_openscap >= 0.7.2 )
```suggestion
## 6.5 Slow queries due to many message records in database
```

2019-11-18 12:48 UTC, tbrisker commented on plugins/foreman_openscap/1.0/index.md
> +## 6.6 Cleaning up reports without OpenSCAP proxy ( foreman_openscap >= 0.8.4 )
```suggestion
## 6.6 Cleaning up reports without OpenSCAP proxy
```

2019-11-18 13:27 UTC, ares reviewed
left few comments that can but don't have to be addressed, functionality wise, all is covered i believe

2019-11-18 13:27 UTC, ares commented on plugins/foreman_openscap/1.0/index.md
> +    <td>0.3.0</td>
I guess we could drop old version that are no longer supported, but that is unrelated and can be done separately in future

2019-11-18 13:27 UTC, ares commented on plugins/foreman_openscap/1.0/index.md
> +# 3. Upgrading from 0.4.x
I guess we could drop this chapter completely

2019-11-19 08:33 UTC, xprazak2 commented
Updated, I am not sure how useful the compatibility matrix is, but in theory we should include puppet_foreman_scap-client and ansible-foreman_scap_client as well and I really do not want to maintain table that large. 

I would replace it with 'rpms in repos for given foreman version are compatible' approach.

2019-11-19 08:41 UTC, tbrisker requested changes
Almost there! a couple of small comments. I'd be fine with dropping the compatibility chart and just say which foreman version(s) the 1.x plugin version is compatible with - so someone reading this manual will know they need foreman 1.23 and can't just install 1.0 on top of their ancient foreman 1.8

2019-11-19 08:41 UTC, tbrisker commented on plugins/foreman_openscap/1.0/index.md
> +robots: noindex
This should be commented here, i meant uncomment it on the older versions of the manual so google stops indexing them and indexes this version instead

2019-11-19 08:41 UTC, tbrisker commented on plugins/foreman_openscap/1.0/index.md
> +```
This should be unindented so it can be copy-pasted (yaml is very sensitive to spaces)

2019-11-19 08:41 UTC, tbrisker commented on plugins/foreman_openscap/1.0/index.md
> +```
unindent here as well

2019-11-19 11:42 UTC, tbrisker approved these changes
Thanks @xprazak2 !

2019-11-19 11:48 UTC, merged