Add scl for 2.x installer options generation
theforeman/theforeman.org pull request #1606
Opened 2020-06-05 14:24 UTC by upadhyeammit

From 2.0 we need ruby from scl and kafo-export-params also requires scl. Adding this change which is working for 1.y and 2.y both versions.

2020-06-05 14:26 UTC, upadhyeammit commented
@ekohl request to review. Thank You !

2020-06-05 14:41 UTC, ekohl commented on scripts/installer/entrypoint.sh
> +  source scl_source enable rh-ruby25
tfm should already pull in the correct Ruby SCL so I think this is redundant
```suggestion
```

2020-08-11 10:45 UTC, ekohl requested changes

2020-08-11 10:45 UTC, ekohl commented on scripts/installer/Dockerfile
> +RUN yum -y install foreman-release-scl
This package was dropped in the latest version, but for the past few releases it has only depended on `centos-release-scl-rh`
```suggestion
RUN yum -y install centos-release-scl-rh
```

2020-09-04 07:03 UTC, upadhyeammit commented
@ekohl replaced scl package to centos-release-scl-rh , request to check, thank you !

2020-09-04 09:56 UTC, ekohl approved these changes
Thanks!

2020-09-04 09:56 UTC, merged