Drop foreman-release-scl for Katello nightly
theforeman/theforeman.org pull request #1647
Opened 2020-07-09 17:39 UTC by ehelms

2020-07-09 17:41 UTC, jlsherrill approved these changes

2020-07-16 11:49 UTC, ekohl requested changes

2020-07-16 11:49 UTC, ekohl commented on plugins/katello/nightly/installation/index.md
> +yum -y install centos-release-scl
```suggestion
yum -y install centos-release-scl-rh
```

2022-01-17 13:23 UTC, lzap commented
I guess this can be closed?

2022-01-17 13:23 UTC, closed without merging

2022-01-17 13:27 UTC, ekohl commented
Yes, fixed in 7ccc427e3c1fa6db37c15ec4c5192eb3f57b9025.