Add Katello 3.16 El8 warning
theforeman/theforeman.org pull request #1650
Opened 2020-07-15 13:51 UTC by ianballou

2020-07-16 11:47 UTC, ekohl approved these changes

2020-07-16 11:47 UTC, ekohl requested changes

2020-07-16 11:47 UTC, ekohl commented on plugins/katello/3.16/release_notes/release_notes.md
> +* Katello 3.16 is not compatible with EL8, but Katello 4.0 will be.
This might be confusing since it can manage EL8 clients. I'd explicitly state it's about deploying Katello itself.

2020-07-16 22:10 UTC, ianballou commented
@ekohl should be all set now.

2020-07-17 07:48 UTC, tbrisker commented
@ianballou please also add a line about it to the 2.1 headline feature about el8 support - https://github.com/theforeman/theforeman.org/blob/gh-pages/_includes/manuals/2.1/1.2_release_notes.md

2020-07-21 14:05 UTC, tbrisker approved these changes
Thanks @ianballou !

2020-07-21 14:05 UTC, merged