Add CVE-2020-14334 to security page
theforeman/theforeman.org pull request #1654
Opened 2020-07-29 12:24 UTC by ezr-ondrej

2020-07-29 12:45 UTC, tbrisker requested changes

2020-07-29 12:45 UTC, tbrisker commented on security.md
> +* Fix released in Foreman 2.1
the fix will be in Foreman 2.2.0, 2.1.1 and 2.0.2 and higher

2020-07-29 12:45 UTC, tbrisker commented on security.md
> +*Mitigation:* change cache directory mode `o-r`.
please specify which directories

2020-07-29 12:45 UTC, tbrisker commented on security.md
> +* Affects RPM installations
since which foreman version?

2020-07-29 12:55 UTC, ekohl commented on security.md
> +* Affects RPM installations
It was part of https://github.com/theforeman/foreman-packaging/commit/847450fab873380fc50af885c67735f8f7abf05e which is titled `Import foreman`. Prior to that RPM specs were in foreman.git and was introduced in https://github.com/theforeman/foreman/commit/d30ac557d1d260bfdae13164cd83deca27c371cc. So my guess is Foreman 1.3 when using RPMs and the file cache backend. That means users of memcached are unaffected by this particular bug, though that does listen on a TCP port which is usually also accessible by local users.

2020-07-30 09:45 UTC, ezr-ondrej commented on security.md
> +* Affects RPM installations
Thanks :heart: I was not able to find it out, I did not know about the switch to packaging repo :)

2020-07-30 09:46 UTC, ezr-ondrej commented on security.md
> +* Affects RPM installations
Altough back then there might not be any sensitive information in the cache... :thinking:

2020-07-30 09:56 UTC, ekohl commented on security.md
> +*Mitigation:* change cache directory mode `o-r` on `/run/foreman`.
This is not a correct mitigation because it's lost at reboot. You must manually change the tmpfiles as well.

2020-07-30 10:00 UTC, ekohl commented on security.md
> +* Affects RPM installations
OAuth was added in https://github.com/theforeman/foreman/commit/fceb1f895c20019ad71863d23316a446c216845e, released in version 1.1 and already used settings. Caching of settings was added in https://github.com/theforeman/foreman/commit/d9a2ebac6e9ec0082e60265b794f54a29a1f7e65, also in 1.1.

2020-07-30 10:01 UTC, ekohl commented
Do we want to suggest to rotate OAuth keys, or at least provide instructions? Are there other secrets there that might have leaked?

2020-07-30 10:08 UTC, ezr-ondrej commented on security.md
> +* Affects RPM installations
There are some passwords, those should be considered compromised as well if there was a possibility to use this vulnerability.
https://github.com/search?q=org%3Atheforeman+%22encrypted+%3D%3E+true%22&type=Code

2020-07-30 10:18 UTC, ezr-ondrej commented
I've tried to suggest the rotation of OAuth keys and passwords, but I'm not sure if we should provide more information.

List of settings that might have been affected: https://github.com/search?q=org%3Atheforeman+%22encrypted+%3D%3E+true%22&type=Code

2020-07-30 10:19 UTC, ezr-ondrej commented on security.md
> +*Mitigation:* change cache directory mode `o-r` on `/run/foreman`.
Change that to advise the temfile rewrite from `/etc/tmpfiles.d`

2020-08-03 14:40 UTC, tbrisker commented on security.md
> +Additionaly it's better to rotate the OAuth keys and Remote Execution passwords
```suggestion
In case the system may have been accessed locally by an un-trusted user, it may be prudent to change and secrets stored in the settings, such as OAuth keys or remote execution passwords.
```

2020-08-03 14:40 UTC, tbrisker commented on security.md
> +To do so, create a file `/etc/tmpfiles.d/foreman.conf` with following content and reboot the system.
This file should already be present if i'm not mistaken? Also, iiuc this modification is only needed so the change survives reboots, the user can also manually `chmod` the folder for the currently running instance without requiring a full reboot.

2020-08-03 14:53 UTC, ekohl commented on security.md
> +To do so, create a file `/etc/tmpfiles.d/foreman.conf` with following content and reboot the system.
No, we ship to `/usr/lib/tmpfiles.d/foreman.conf`. The downside of creating `/etc/tmpfiles.d/foreman.conf` is that if we want to make further changes in the future, then users won't get them. However, users probably also shouldn't change `/usr/lib`.

Changing in `/usr/lib/tmpfiles.d` means they get updated in the future, but if they update from unsupported-x.y to unsupported-x.z then they lose the protection. OTOH, they should just update to a supported version.

I'm conflicted on the best advise, but slightly leaning to `/usr/lib/tmpfiles.d`.

@theforeman/packaging what would you advise?

2020-08-03 15:20 UTC, evgeni commented on security.md
> +To do so, create a file `/etc/tmpfiles.d/foreman.conf` with following content and reboot the system.
etc is for overrides if package defaults, and thats exactly whats needed here. So IMHO etc and the hint to remove that file after upgrading to a fixed release.

2020-08-03 15:20 UTC, dgoetz commented on security.md
> +To do so, create a file `/etc/tmpfiles.d/foreman.conf` with following content and reboot the system.
systemd-tmpfiles.d does not allow for drop-ins like with unit files, but it explicitly mentions splitting the configuration for easier overwriting of configuration.

```
Each configuration file shall be named in the style of package.conf or package-part.conf. The second variant should be used when it is desirable to make it easy to override just this part of configuration. 
```

So perhaps it would make sense to split it up and store values in `/usr/lib/tmpfiles.d` where packages should install the files? Not sure if this would mess things up, but perhaps an idea for the future. But I am also pro `/usr/lib/tmpfiles.d`.

For those already having created local configuration in `/etc/tmpfiles.d`, it makes sense to advice them to adjust configuration, but I would leave this to documentation and perhaps it is possible to have a migration in the foreman-installer which checks for the CVE, links to it and provides a simple sed for mitigation?

2020-08-07 09:51 UTC, ezr-ondrej commented on security.md
> +To do so, create a file `/etc/tmpfiles.d/foreman.conf` with following content and reboot the system.
I updated the suggestion to update of the `/usr/lib/tmpfile.d` as @ekohl is mentioning, the next upgrade should be to a supported version, so this solution will leave the least traces in the system.

2020-08-10 07:18 UTC, lzap commented on security.md
> +
This is not enough, the permission will be fixed on next reboot or after 24 hours when the systemd timer fires off. I suggest to also recommend changing the permissions immediately on the directory itself using `chmod`. Look:

```
[root@box lzap]# ll -ad /tmp/test
drwx------. 2 root root 40 10. srp 09.17 /tmp/test
[root@box lzap]# cat /usr/lib/tmpfiles.d/test.conf
d /tmp/test 0700 root root -
[root@box lzap]# vim /usr/lib/tmpfiles.d/test.conf
[root@box lzap]# ll -ad /tmp/test
drwx------. 2 root root 40 10. srp 09.17 /tmp/test
[root@box lzap]# systemd-tmpfiles --create
[root@box lzap]# ll -ad /tmp/test
drwxrwxrwx. 2 root root 40 10. srp 09.17 /tmp/test
```

2020-08-10 09:51 UTC, ekohl commented on security.md
> +For the change to have effect immediatelly run `systemd-tmpfiles --create` or change the directory mode manually by running `chmod 755 /run/foreman`.
I like the `systemd-tmpfiles --create` suggestion since you verify the state post-reboot. I'd leave off the chmod command. Also note you have `755` in the current command

2020-08-10 09:57 UTC, ezr-ondrej commented on security.md
> +For the change to have effect immediatelly run `systemd-tmpfiles --create` or change the directory mode manually by running `chmod 755 /run/foreman`.
Dropping the `chmod` :+1:

2020-08-10 11:29 UTC, lzap approved these changes

2020-08-10 11:36 UTC, ekohl approved these changes
Small language nit, otherwise :+1:

2020-08-10 11:36 UTC, ekohl commented on security.md
> +To do so in a manner that survives reboot, update a file `/usr/lib/tmpfiles.d/foreman.conf`.
It feels more natural to use the definitive article here since we know what we're talking about.
```suggestion
To do so in a manner that survives reboot, update the file `/usr/lib/tmpfiles.d/foreman.conf`.
```

2020-08-10 11:37 UTC, ezr-ondrej commented on security.md
> +To do so in a manner that survives reboot, update a file `/usr/lib/tmpfiles.d/foreman.conf`.
:+1:  thanks, commited.

2020-08-10 22:15 UTC, ezr-ondrej commented
@tbrisker, any more comments? :)

2020-08-11 06:42 UTC, tbrisker commented on security.md
> +In case the system may have been accessed locally by an un-trusted user, it may be prudent to change and secrets stored in the settings, such as OAuth keys or remote execution passwords.
just a tiny typo:
```suggestion
In case the system may have been accessed locally by an un-trusted user, it may be prudent to change any secrets stored in the settings, such as OAuth keys or remote execution passwords.
```

2020-08-11 08:58 UTC, ezr-ondrej commented on security.md
> +In case the system may have been accessed locally by an un-trusted user, it may be prudent to change and secrets stored in the settings, such as OAuth keys or remote execution passwords.
:+1: Done.

2020-08-11 08:59 UTC, tbrisker approved these changes
Thanks @ezr-ondrej !

2020-08-11 08:59 UTC, merged