Add Katello 3.17 release docs
theforeman/theforeman.org pull request #1669
Opened 2020-08-28 15:23 UTC by chris1984

2020-09-01 16:54 UTC, jturel commented
API docs are missing & there aren't any release notes - feel free to reach out to the team to help put those together but the changelog should be a good guide to pluck the highlights!

2020-09-01 16:58 UTC, jturel commented on _data/plugins/katello.yml
> +    display: "3.17 RC 1"
nit: "RC2" (no space)

2020-09-01 21:19 UTC, chris1984 commented
@jturel updated

2020-09-02 14:25 UTC, jturel approved these changes
ACK!

2020-09-03 12:19 UTC, tbrisker reviewed
not sure why, but the apidocs seem to have both `en` and `en_US` versions, we can probably drop one of them.

2020-09-03 13:47 UTC, chris1984 commented
@tbrisker 3.16 and 3.16 have it too, so I copied it to match. 

https://github.com/theforeman/theforeman.org/tree/gh-pages/plugins/katello/3.16/api/apidoc

https://github.com/theforeman/theforeman.org/tree/gh-pages/plugins/katello/3.15/api/apidoc

2020-09-03 15:34 UTC, chris1984 commented
@jturel updated with removing the `en_US` files and api docs still render correctly.

2020-09-03 16:51 UTC, jturel requested changes
Still seeing a lot of JSON which makes me think you missed this step:

https://github.com/theforeman/tool_belt/blob/8569eff9750ad953247b3ffb34c6d0bf01ff746e/procedures/katello/branch.md.erb#L55-L56

2020-09-03 16:56 UTC, chris1984 commented
@jturel yeah that was my bad, updated to remove the .json files

2020-09-03 17:08 UTC, jturel commented
Looks like all feedback is addressed. Merging so we can get the announcement out!

2020-09-03 17:08 UTC, merged