Update installer options for v 2.2
theforeman/theforeman.org pull request #1676
Opened 2020-09-09 15:09 UTC by upadhyeammit

2020-09-21 11:53 UTC, tbrisker approved these changes
thanks @upadhyeammit

2020-09-21 11:54 UTC, tbrisker requested changes
actually, we probably want to copy these changes to the nightly manual as well

2020-09-21 12:03 UTC, ekohl reviewed
Looks good, but as @tbrisker said: nightly deserves the same.

2020-09-21 12:03 UTC, ekohl commented on _includes/manuals/2.2/3.2.2_installer_options.md
> +        <td>Enable 'foreman_plugin_statistics' puppet module (<a href="/plugins/foreman_statistics">foreman_statistics</a>)</td>
I'm now remembering I wrote the code for this and happy that it still works. Note how it's the Foreman manual vs the GH project :)

2020-09-24 06:42 UTC, upadhyeammit commented
> actually, we probably want to copy these changes to the nightly manual as well
I forgot most of the time, will keep this in mind when updating latest stable next time.

2020-09-24 07:30 UTC, tbrisker approved these changes
Thanks @upadhyeammit !

2020-09-24 07:30 UTC, merged