Update method for retrieving 'oauth_consumer_key' and 'oauth_consumer…
theforeman/theforeman.org pull request #1743
Opened 2020-12-08 12:04 UTC by illumino

…_secret'

https://projects.theforeman.org/issues/31472
https://community.theforeman.org/t/web-site-manual-2-3-0-out-of-date-instructions-on-obtaining-oauth-consumer-key-and-oauth-consumer-secret/21586

2020-12-10 13:33 UTC, ekohl requested changes
I would still prefer to get them via `foreman-rake config | grep oauth` or `foreman-rake -- config -k oauth_consumer_key`. Those are official interfaces that I would support. They use the application logic. When you don't use the installer, you can leave them out of `settings.yaml` and only set them in the database. Following the application logic prepares us better for a future where we might want to support containers.

2021-10-14 10:33 UTC, illumino commented
@ekohl did the update not meet your requirements?
Or did the changes just get missed?

2021-10-20 12:32 UTC, ekohl commented
>  Or did the changes just get missed?

This. My apologies for keeping this open so long.

2021-10-20 12:32 UTC, ekohl approved these changes

2021-10-20 12:33 UTC, merged