Release notes for Foreman 2.2.2
theforeman/theforeman.org pull request #1745
Opened 2020-12-10 14:58 UTC by upadhyeammit

2020-12-10 15:41 UTC, tbrisker commented on _includes/manuals/2.2/1.2_release_notes.md
>  * VNC console connection may fail to connect due to browser security settings. This will be fixed in 2.2.2 and 2.3.0. The patch fixing it can be safely applied manually if needed. ([#31317](https://p
This is fixed now, we can drop the known issues section

2020-12-14 13:05 UTC, tbrisker approved these changes

2020-12-16 19:51 UTC, tbrisker requested changes
I think you missed something in the last push, the release notes are missing now

2020-12-17 04:43 UTC, upadhyeammit commented
> I think you missed something in the last push, the release notes are missing now

pushed the corrected changes, thank you !

2020-12-17 07:29 UTC, tbrisker approved these changes
Thanks @upadhyeammit !

2020-12-17 07:29 UTC, merged