Add REX intro
theforeman/theforeman.org pull request #1780
Opened 2021-02-17 20:41 UTC by ares

I know I said this would be more for opensource.com, however I wanted to continue providing intros. And that felt more like a Foreman specific blog post. I'd kindly ask for review and ideally merging this faster than the last post, it's more than a month since the last one already. I'm happy to merge any language suggestions :-)

2021-02-18 16:11 UTC, melcorr requested changes
Few nitpicks and can we s/puppet/Puppet please :) 
Thanks

2021-02-18 16:11 UTC, melcorr commented on _posts/2021-02-17-introduction-to-the-remote-execution-plugin.md
> +on one or more of the Foreman hosts. Then we’ll look at some real-world use cases of
```suggestion
on one or more Foreman hosts. Then we’ll look at some real-world use cases of
```

2021-02-18 16:11 UTC, melcorr commented on _posts/2021-02-17-introduction-to-the-remote-execution-plugin.md
> +useful SSH jobs automation. We’ll show how to deploy puppet agent on the Foreman host and
```suggestion
useful SSH jobs automation. We’ll show how to deploy the Puppet agent on the Foreman host and
```

2021-02-18 16:11 UTC, melcorr commented on _posts/2021-02-17-introduction-to-the-remote-execution-plugin.md
> +To add the remote execution feature, a plugin for Foreman and Smart proxy is required.
```suggestion
To add the remote execution feature, a plugin for Foreman and Smart Proxy is required.
```

2021-02-18 16:11 UTC, melcorr commented on _posts/2021-02-17-introduction-to-the-remote-execution-plugin.md
> +The installer can handle the installation and the initial configuration of both for you.
```suggestion
The installer can handle both the installation and the initial configuration.
```

2021-02-18 16:11 UTC, melcorr commented on _posts/2021-02-17-introduction-to-the-remote-execution-plugin.md
> +The Foreman installer can be run repeatedly. In case you haven’t done manual modifications
```suggestion
The Foreman installer can be run repeatedly. As long as you haven’t done manual modifications
```

2021-02-18 16:11 UTC, melcorr commented on _posts/2021-02-17-introduction-to-the-remote-execution-plugin.md
> +run, therefore you can simply just add new params. The bare minimum to install or extend
```suggestion
run, therefore you can simply just add new parameters. The bare minimum to install or extend
```

2021-02-18 16:11 UTC, melcorr commented on _posts/2021-02-17-introduction-to-the-remote-execution-plugin.md
> +If you plan to use CLI, install a plugin for that, so you can use REX CLI commands by
```suggestion
If you plan to use CLI commands, you must install a plugin for that, so you can use REX CLI commands by
```

2021-02-18 16:11 UTC, melcorr commented on _posts/2021-02-17-introduction-to-the-remote-execution-plugin.md
> +and Foreman can connect to it. Navigate to some existing host detail page and click the
```suggestion
and Foreman can connect to it. Navigate to an existing host detail page and click the
```

2021-02-18 16:11 UTC, melcorr commented on _posts/2021-02-17-introduction-to-the-remote-execution-plugin.md
> +The password will be stored only for necessary time to execute the script,
```suggestion
The password is stored only for the time it takes to execute the script,
```

2021-02-18 16:11 UTC, melcorr commented on _posts/2021-02-17-introduction-to-the-remote-execution-plugin.md
> +protected by a passphrase or you need to specify it for every job, similarly to how we
```suggestion
protected by a passphrase or you need to specify it for every job, similar to how we
```

2021-02-18 16:11 UTC, melcorr commented on _posts/2021-02-17-introduction-to-the-remote-execution-plugin.md
> +However you can use a more elegant way and do it from Foreman directly. For that we’ll
```suggestion
However, you can use a more elegant way and do it from Foreman directly. For that we’ll
```

2021-02-18 16:11 UTC, melcorr commented on _posts/2021-02-17-introduction-to-the-remote-execution-plugin.md
> +To do that, use the following template content
```suggestion
To do that, use the following template content:
```

2021-02-18 16:11 UTC, melcorr commented on _posts/2021-02-17-introduction-to-the-remote-execution-plugin.md
> +puppet agent. However if you start with Foreman and want to manage an existing
```suggestion
puppet agent. However, if you start with Foreman and want to manage an existing
```

2021-02-18 16:11 UTC, melcorr commented on _posts/2021-02-17-introduction-to-the-remote-execution-plugin.md
> +To deploy a puppet agent, we need to install the a package, create a configuration file
```suggestion
To deploy a puppet agent, we need to install a package, create a configuration file
```

2021-02-18 16:11 UTC, melcorr commented on _posts/2021-02-17-introduction-to-the-remote-execution-plugin.md
> +assigned to the host. Before we go too far, I want to point out that thanks to the
```suggestion
assigned to the host. Before we continue, I want to point out that thanks to the
```

2021-02-18 16:11 UTC, melcorr commented on _posts/2021-02-17-introduction-to-the-remote-execution-plugin.md
> +configuration and restarts the led service, which is the same code for both cases.
```suggestion
configuration and restarts the LED service, which is the same code for both cases.
```

2021-02-18 16:11 UTC, melcorr commented on _posts/2021-02-17-introduction-to-the-remote-execution-plugin.md
> +REX in next posts too. The user interface for triggering the job is now being greatly
```suggestion
REX in the next posts too. The user interface for triggering the job is now being greatly
```

2021-02-19 13:45 UTC, ares commented
Thanks @melcorr, I've incorporated all your suggestions and capitalized puppet everywhere

2021-02-19 18:46 UTC, merged