Add docs for Azure 2.2.x plugin version
theforeman/theforeman.org pull request #1799
Opened 2021-03-26 17:17 UTC by chris1984

@upadhyeammit 

Amit here are the docs for 2.2.x

2021-03-30 17:05 UTC, upadhyeammit requested changes

2021-03-30 17:05 UTC, upadhyeammit commented on plugins/foreman_azure/2.2.x/index.md
> +* Now, you can also select additional disks for the host. Note that the maximum number of these disks depends on the VM Size selected. Please refer to MSFT documentation for more details.
Is it possible to add link of MSFT documentation?

2021-03-30 17:05 UTC, upadhyeammit commented on plugins/foreman_azure/2.2.x/index.md
> +* Last specification is for the Network Interface. You should select a domain defined under Foreman and then select Azure subnet and Public or Private IP format. Now, you can also select multiple int
Ditto, request to add MSFT documentation.

2021-03-30 17:13 UTC, melcorr reviewed
Tiny nits

2021-03-30 17:13 UTC, melcorr commented on plugins/foreman_azure/2.2.x/index.md
> +This plugin 2.2.x series has no dependency of foreman_azure 1.x as they refer to different Azure APIs. This 2.2.x should be compatible with Foreman 2.0 onwards, but it is recommended to use latest Fo
```suggestion
This plugin 2.2.x series has no dependency on foreman_azure 1.x as they refer to different Azure APIs. This 2.2.x should be compatible with Foreman 2.0 onwards, but it is recommended to use latest Foreman version.
```

2021-03-30 17:13 UTC, melcorr commented on plugins/foreman_azure/2.2.x/index.md
> +* Creation of the Compute Resource requires using of four credentials: Client ID, Client Secret, Subscription ID and Tenant ID.
```suggestion
* Creation of the Compute Resource requires using four credentials: Client ID, Client Secret, Subscription ID and Tenant ID.
```

2021-03-30 17:14 UTC, melcorr commented
I'm going to link from this PR to a new issue in the new docs, and whenever I get a chance, I'll update there also: https://docs.theforeman.org/nightly/Provisioning_Guide/index-foreman-el.html#provisioning-cloud-instances-azure_provisioning

2021-03-30 18:50 UTC, chris1984 commented on plugins/foreman_azure/2.2.x/index.md
> +This plugin 2.2.x series has no dependency of foreman_azure 1.x as they refer to different Azure APIs. This 2.2.x should be compatible with Foreman 2.0 onwards, but it is recommended to use latest Fo
Fixed.

2021-03-30 18:50 UTC, chris1984 commented on plugins/foreman_azure/2.2.x/index.md
> +* Creation of the Compute Resource requires using of four credentials: Client ID, Client Secret, Subscription ID and Tenant ID.
Fixed.

2021-03-30 18:51 UTC, chris1984 commented on plugins/foreman_azure/2.2.x/index.md
> +* Last specification is for the Network Interface. You should select a domain defined under Foreman and then select Azure subnet and Public or Private IP format. Now, you can also select multiple int
Fixed.

2021-03-30 18:51 UTC, chris1984 commented on plugins/foreman_azure/2.2.x/index.md
> +* Now, you can also select additional disks for the host. Note that the maximum number of these disks depends on the VM Size selected. Please refer to MSFT documentation for more details.
Fixed.

2021-03-30 18:51 UTC, chris1984 commented
@melcorr @upadhyeammit updated, let me know how that looks.

2021-04-06 12:43 UTC, upadhyeammit approved these changes
LGTM!

2021-04-06 12:44 UTC, merged