Added CVE-2021-3584
theforeman/theforeman.org pull request #1845
Opened 2021-06-17 08:34 UTC by lzap

SSIA

2021-06-17 08:34 UTC, lzap commented on security.md
> +* Fix released in Foreman 2.4.1, 2.5.1 and higher
To be confirmed by @upadhyeammit

2021-06-17 08:58 UTC, ekohl requested changes

2021-06-17 08:58 UTC, ekohl commented on security.md
> +Sendmail location and arguments, available via Administer - Settings, both accept arbitrary strings and pass them into shell. By default, only Foreman super administrator can access settings.
```suggestion
Sendmail location and arguments, available via Administer - Settings, both accept arbitrary strings and pass them into shell. By default, only Foreman super administrators can access settings.
```

2021-06-17 08:58 UTC, ekohl commented on security.md
> +*Mitigation:* Verify the both settings and remove edit_settings permissions to all roles and users until fixed. Alternatively, create settings named sendmail_location and sendmail_arguments in `setti
```suggestion
*Mitigation:* Verify the both settings and remove edit_settings permissions from all roles and users until fixed. Alternatively, create settings named `sendmail_location` and `sendmail_arguments` in `settings.yaml` file to override the UI and make the values read-only. Note that the installer will remove these again.
```

2021-06-17 08:58 UTC, ekohl commented on security.md
> +* Affects Foreman veersion 1.15 and higher
```suggestion
* Affects Foreman version 1.15 and higher
```

2021-06-17 10:28 UTC, lzap commented on security.md
> +* Fix released in Foreman 2.4.1, 2.5.1 and higher
Confirmed by Amit thanks.

2021-06-17 10:28 UTC, lzap commented on security.md
> +* Affects Foreman veersion 1.15 and higher
Looks quite Dutch :-) veersion 🇳🇱

2021-06-17 10:29 UTC, lzap commented
Oh batch commit feature is nice, please squash on merge.

2021-06-17 10:33 UTC, ekohl commented on security.md
> +* Affects Foreman veersion 1.15 and higher
The Dutch translation is `versie`. `veer` means feather or spring (the metal kind that you can compress and it'll take its old shape again) but there's no `veersion` ;)

2021-06-17 10:35 UTC, ekohl commented on security.md
> +*Mitigation:* Verify the both settings and remove edit_settings permissions from all roles and users until fixed. Alternatively, create settings named `sendmail_location` and `sendmail_arguments` in
Just wondering: will users understand that they really should use `:sendmail_location`? Perhaps an example section is good?

2021-06-17 11:39 UTC, tbrisker commented on security.md
> +*Mitigation:* Verify the both settings and remove edit_settings permissions from all roles and users until fixed. Alternatively, create settings named `sendmail_location` and `sendmail_arguments` in
```suggestion
*Mitigation:* Verify the value of both settings and remove the `edit_settings` permissions from any untrusted users until fixed. Alternatively, create settings named `sendmail_location` and `sendmail_arguments` in `settings.yaml` file to override the UI and make the values read-only. Note that the installer will remove these again.
```

2021-06-17 11:41 UTC, tbrisker commented on security.md
> +Sendmail location and arguments, available via Administer - Settings, both accept arbitrary strings and pass them into shell. By default, only Foreman super administrators can access settings.
```suggestion
Sendmail location and arguments, available via Administer - Settings, both accept arbitrary strings and pass them into shell. By default, Foreman administrators as well as "Manager" and "System Administrator" roles can modify settings.
```

2021-06-18 11:03 UTC, lzap commented
Added example, please squash.

2021-06-22 11:16 UTC, ohadlevy commented
@lzap no need to ack the reporter?

2021-06-23 11:28 UTC, lzap commented
Good catch, amended. Cheers @ohadlevy ! :-)

2021-06-23 12:30 UTC, ekohl commented on security.md
> +* Affects Foreman veersion 1.15 and higher
Typo is still here

2021-06-23 12:32 UTC, lzap commented on security.md
> +* Affects Foreman veersion 1.15 and higher
Damn, rebased.

2021-06-23 12:54 UTC, ekohl commented on security.md
> +*Mitigation:* Verify the both settings and remove edit_settings permissions from all roles and users until fixed. Alternatively, create settings named `sendmail_location` and `sendmail_arguments` in
I still think this is better. Otherwise users may create an entry that ends up being unused. A literal example is even better.

2021-06-23 13:59 UTC, lzap commented on security.md
> +*Mitigation:* Verify the both settings and remove edit_settings permissions from all roles and users until fixed. Alternatively, create settings named `sendmail_location` and `sendmail_arguments` in
Done.

2021-06-24 11:53 UTC, ekohl commented on security.md
> +Sendmail location and arguments, available via Administer - Settings, both accept arbitrary strings and pass them into shell. By default, only Foreman super administrator can access settings.
Apologies for not catching this the first time
```suggestion
Sendmail location and arguments, available via Administer - Settings, both accept arbitrary strings and pass them into shell. By default, only Foreman super administrator can access settings. However, non-admin users can be granted the permission to edit settings.
```

2021-06-24 11:56 UTC, ekohl commented on security.md
> +    :sendmail_arguments: "-i"
````suggestion
*Mitigation 1:* Verify the both settings and remove edit_settings permissions to all roles and users until fixed.

*Mitigation 2:* Create entries in `settings.yaml` to override UI settings and make them read-only. Note that the installer will revert these changes. [#32827](https://projects.theforeman.org/issues/32827) will add options to the installer which makes it supported.

```yaml
:sendmail_location: "/usr/sbin/sendmail"
:sendmail_arguments: "-i"
```
````

2021-06-25 09:08 UTC, lzap commented
Merged thanks!

2021-07-12 10:39 UTC, tbrisker commented on security.md
> +Sendmail location and arguments, available via Administer - Settings, both accept arbitrary strings and pass them into shell. By default, only Foreman super administrator can access settings.
This is incorrect. By default users with the `Manager` or `System admin` roles also have permission to edit settings.

2022-01-17 13:20 UTC, lzap commented on security.md
> +Sendmail location and arguments, available via Administer - Settings, both accept arbitrary strings and pass them into shell. By default, only Foreman super administrator can access settings.
Corrected.

2022-01-17 13:20 UTC, lzap commented
Rebased.

2022-03-17 12:39 UTC, lzap commented
@ekohl mind finishing this up? Thanks!

2023-02-19 11:26 UTC, closed without merging