EL7 & Ubuntu 18.04 deprecations for 3.0 & nightly
theforeman/theforeman.org pull request #1894
Opened 2021-09-07 16:27 UTC by ekohl

This follows the [RFC].

[RFC]: https://community.theforeman.org/t/deprecation-plans-for-foreman-on-el7-debian-10-and-ubuntu-18-04/25008

2021-09-07 16:38 UTC, melcorr requested changes
Two small things on reading. 
I question whether "heads up" is the most clear way to say this, but if that phrase is ubiquitous enough for you to use it, it's probably understood by all!!

2021-09-07 16:38 UTC, melcorr commented on _includes/manuals/3.0/1.2_release_notes.md
> +Users are encouraged to upgrade to Ubuntu 20.04 either on Foreman 2.5 or 3.0 but Ubuntu 18.04 remain supported until Foreman 2.5 and 3.0 are end of life.
```suggestion
Users are encouraged to upgrade to Ubuntu 20.04 either on Foreman 2.5 or 3.0 but Ubuntu 18.04 will remain supported until Foreman 2.5 and 3.0 are end of life.
```

2021-09-07 16:38 UTC, melcorr commented on _includes/manuals/3.0/1.2_release_notes.md
> +For fresh installations EL8 should considered the preferred target.
```suggestion
For fresh installations, EL8 should considered the preferred target.
```

2021-09-08 08:28 UTC, ekohl commented
>  I question whether "heads up" is the most clear way to say this, but if that phrase is ubiquitous enough for you to use it, it's probably understood by all!!

I can change it to early notice.

2021-09-08 08:50 UTC, melcorr approved these changes
Reads well.

2021-09-08 11:59 UTC, upadhyeammit approved these changes

2021-09-08 12:02 UTC, upadhyeammit commented
@ekohl thank you for the notes. @melcorr thanks for review. Merging this one!

2021-09-08 12:04 UTC, merged