Adding GPG for Foreman 3.1
theforeman/theforeman.org pull request #1915
Opened 2021-11-09 18:15 UTC by Odilhao

2021-11-09 18:17 UTC, evgeni commented on security.md
> +        <td>FIXME: fingerprint</td>
fixme :P

2021-11-09 18:17 UTC, evgeni requested changes

2021-11-09 18:17 UTC, evgeni commented on security.md
> +        <td style='white-space:nowrap'>FIXME: end date</td>
fixme

2021-11-09 18:28 UTC, Odilhao commented on security.md
> +        <td>FIXME: fingerprint</td>
Done xD

2021-11-10 14:59 UTC, ekohl approved these changes

2021-11-11 10:17 UTC, merged