Update headline features for Foreman 3.1
theforeman/theforeman.org pull request #1923
Opened 2021-11-25 17:21 UTC by upadhyeammit

2021-11-25 17:22 UTC, upadhyeammit commented on _includes/manuals/3.1/1.2_release_notes.md
> +#### Improvements and additions to the new Host Details page:
@amirfefer if you think I should add or remove something then request to comment.

2021-11-25 17:24 UTC, upadhyeammit commented
@tbrisker @evgeni @ezr-ondrej @melcorr if you think I should remove something from headline features or add some then request to comment and review.

2021-11-25 17:33 UTC, evgeni commented
I have nothing to add/remove.

2021-11-27 06:37 UTC, ezr-ondrej commented
I believe we are supporting Puppet 7 now, don't we?
At maintainers meeting, we were disscussing that this was the last piece in the puzzle for Puppet 7 support https://github.com/theforeman/foreman/pull/8899

2021-11-29 12:49 UTC, upadhyeammit commented
> I believe we are supporting Puppet 7 now, don't we? At maintainers meeting, we were disscussing that this was the last piece in the puzzle for Puppet 7 support [theforeman/foreman#8899](https://github.com/theforeman/foreman/pull/8899)

I have added Puppet 7 change in snippets. Accordingly cherry picked the https://github.com/theforeman/foreman/pull/8899 in core as well

2021-11-29 12:50 UTC, melcorr requested changes
Something small

2021-11-29 12:50 UTC, melcorr commented on _includes/manuals/3.1/1.2_release_notes.md
> +New PatternFly 4 search bar:
```suggestion

```

2021-11-29 17:01 UTC, melcorr requested changes
Some small comments but otherwise good!

2021-11-29 17:01 UTC, melcorr commented on _includes/manuals/3.1/1.2_release_notes.md
> +New modals for build button and BMC Power Management is available which improves exprience of new Host Details page.
```suggestion
New modals for a build button and BMC Power Management is available, which improves exprience of new Host Details page.
```

2021-11-29 17:01 UTC, melcorr commented on _includes/manuals/3.1/1.2_release_notes.md
> +There is addition of rake task foreman-rake purge:puppet to purge puppet data if Puppet ENC functionality is not required.
```suggestion
A new foreman-rake purge:puppet task has been added to purge Puppet data if Puppet ENC functionality is not required.
```

2021-11-30 09:09 UTC, ezr-ondrej approved these changes

2021-11-30 09:11 UTC, melcorr approved these changes
Thank you !

2021-11-30 09:43 UTC, upadhyeammit commented
@melcorr @ezr-ondrej thanks for review! Merging this now.

2021-11-30 09:43 UTC, merged