Branch manual for Foreman 3.2
theforeman/theforeman.org pull request #1949
Opened 2022-02-01 16:35 UTC by upadhyeammit

2022-02-08 12:33 UTC, melcorr requested changes
Few small comments I hope might make things clearer.

2022-02-08 12:33 UTC, melcorr commented on _includes/manuals/3.2/1.1_architecture.md
> +A [Smart-Proxy](manuals/{{page.version}}/index.html#4.3SmartProxies) is located on or near a machine that performs a specific function and helps foreman orchestrate the process of commissioning a new
```suggestion
A [Smart-Proxy](manuals/{{page.version}}/index.html#4.3SmartProxies) is located on or near a machine that performs a specific function and helps Foreman orchestrate the process of commissioning a new host. Placing the Smart Proxy on or near to the actual service will also help reduce latency in large distributed organizations.
```

2022-02-08 12:33 UTC, melcorr commented on _includes/manuals/3.2/1.1_architecture.md
> +foreman installation supports unattended installations then other
```suggestion
Foreman installation supports unattended installations, then other
```

2022-02-08 12:33 UTC, melcorr commented on _includes/manuals/3.2/1.1_architecture.md
> +smart proxy manages remote services and is generally installed with all
```suggestion
Smart Proxy manages remote services and is generally installed with all
```

2022-02-08 12:33 UTC, melcorr commented on _includes/manuals/3.2/1.2_release_notes.md
> +For fresh installations, EL8 should considered the preferred target.
```suggestion
For fresh installations, it is advisable to install on EL8.
```

2022-02-08 12:33 UTC, melcorr commented on _includes/manuals/3.2/1.2_release_notes.md
> +Note that this is only support to run Foreman and Foreman Proxy themselves on EL7. Managing EL7 systems remains supported. See [the RFC](https://community.theforeman.org/t/deprecation-plans-for-forem
```suggestion
Note that this support statement refers to running Foreman and Foreman Smart Proxy themselves on EL7. Managing EL7 client systems remains supported. See [the RFC](https://community.theforeman.org/t/deprecation-plans-for-foreman-on-el7-debian-10-and-ubuntu-18-04/25008) for more information.
```

2022-02-08 12:33 UTC, melcorr commented on _includes/manuals/3.2/1.2_release_notes.md
> +Note that this is only support to run Foreman and Foreman Proxy themselves on Debian 10. Managing Debia 10 systems remains supported. See [the RFC](https://community.theforeman.org/t/deprecation-plan
```suggestion
Note that this support statement refers to running Foreman and Foreman Smart Proxy themselves on Debian 10. Managing Debian 10 client systems remains supported. See [the RFC](https://community.theforeman.org/t/deprecation-plans-for-foreman-on-el7-debian-10-and-ubuntu-18-04/25008) for more information.
```

2022-02-08 12:33 UTC, melcorr commented on _includes/manuals/3.2/2.1_quickstart_installation.md
> +* [Provisioning Guide](https://docs.theforeman.org/master/Provisioning_Guide/index-foreman.html)
all these links are broken... we'll need a more clever way to handle these..

2022-02-08 12:50 UTC, ekohl commented
They look like good suggestions. It would be better to first apply these to nightly and then do the branching. Also, I think some of these need to be applied to other releases as well.

2022-02-08 13:01 UTC, melcorr commented
I had intended only to touch the release notes but couldn't resist the architecture section. I'll raise a separate PR for those few changes.

2022-02-09 10:32 UTC, upadhyeammit commented
Rebased on @melcorr changes.

2022-02-11 13:23 UTC, upadhyeammit commented
while we are at branching manuals I also updated the installer options update in same pr.

2022-02-11 13:28 UTC, ekohl approved these changes
Thanks! CI is still running but :+1: once it's green.

2022-02-11 15:10 UTC, melcorr approved these changes

2022-02-14 16:20 UTC, merged