Foreman 3.4 public key
theforeman/theforeman.org pull request #2008
Opened 2022-08-05 14:24 UTC by pcreech

2022-08-05 14:26 UTC, Odilhao approved these changes

2022-08-08 09:36 UTC, ekohl requested changes
I tried to replicate this by importing the GPG secret, but the data in our shared storage looks wrong:
```console
$ VERSION=3.4 ./import_gpg_private 
✔ Copied theforeman/releases/foreman/3.4-gpg to clipboard. Will clear in 45 seconds.
gpg: keybox '/home/ekohl/dev/theforeman-rel-eng/releases/foreman/3.4/gnupg/pubring.kbx' created

Error: empty secret
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
```

There is a gpg passphrase but I don't see the actual key.

@Odilhao next time you review a PR like this, please perform the same steps. This is crucial.

2022-08-08 09:36 UTC, ekohl commented on security.md
> +        <td>FIXME: fingerprint</td>
Please fix this

2022-08-08 13:57 UTC, pcreech commented on security.md
> +        <td>FIXME: fingerprint</td>
*facepalm* whoops, will do.

2022-08-08 13:58 UTC, pcreech commented
@ekohl as far as the key, I'm pretty sure I followed all steps for key generation, but i'll go back and check to see if I can find the breakdown.

2022-08-08 15:25 UTC, ekohl commented
> @ekohl as far as the key, I'm pretty sure I followed all steps for key generation, but i'll go back and check to see if I can find the breakdown.

I tried to look at the git log, but I'm not sure what went wrong. Perhaps you mistyped a passphrase or something and it stored garbage?

2022-08-08 15:50 UTC, Odilhao commented
```
gpg: keybox 'theforeman-rel-eng/releases/foreman/3.4/gnupg/pubring.kbx' created
gpg: /home/osousa/code/sat/theforeman-rel-eng/releases/foreman/3.4/gnupg/trustdb.gpg: trustdb created
gpg: key 39D12077F120E13E: public key "Foreman Automatic Signing Key (3.4) <packages@theforeman.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg:       secret keys read: 1
gpg:   secret keys imported: 1
```

2022-08-09 17:55 UTC, pcreech commented on security.md
> +        <td>FIXME: fingerprint</td>
should be fixed

2022-08-09 17:55 UTC, pcreech commented
@ekohl the key should be good to go.

2022-08-10 10:11 UTC, ekohl approved these changes
Thanks!

2022-08-10 10:11 UTC, merged