Add Foreman 3.10 manual
theforeman/theforeman.org pull request #2128
Opened 2024-02-16 13:45 UTC by Griffin-Sullivan

2024-02-16 16:58 UTC, ekohl requested changes

2024-02-16 16:58 UTC, ekohl commented on _includes/manuals/3.10/1.2_release_notes.md
> +#### `ct_command` and `fcct_command` settings replaced with `(fc)ct_location` and `(fc)ct_arguments`
I think we forgot to clear the nightly manual when branching 3.9. Would you mind doing so?

2024-02-22 14:26 UTC, Griffin-Sullivan commented on _includes/manuals/3.10/1.2_release_notes.md
> +### Deprecations
Need to add deprecation for `foreman-maintain backup snapshot`

2024-02-28 13:42 UTC, ekohl approved these changes

2024-02-28 13:42 UTC, merged