Add release notes for 3.13
theforeman/theforeman.org pull request #2196
Opened 2024-11-07 20:21 UTC by ColeHiggins2

2024-11-07 20:23 UTC, ColeHiggins2 commented
@ekohl Do we want to add anything to the headline features, deprecations, and upgrade warnings?

2024-11-12 21:07 UTC, ekohl requested changes
I think we should add a note that Debian 11 is deprecated and will be dropped with Foreman 3.14, but I can do that tomorrow if you'd like. Some inline notes to improve readability.

2024-11-12 21:07 UTC, ekohl commented on _includes/manuals/3.13/1.2_release_notes.md
>  ### Release Notes
I think we can drop this header
```suggestion

```

2024-11-12 21:07 UTC, ekohl commented on _includes/manuals/3.13/1.2_release_notes.md
I think line 3 (`This section will be updated prior to the next release.`) should be removed.

2024-11-13 17:48 UTC, ekohl commented
If you agree, could you merge & include https://github.com/theforeman/foreman-documentation/pull/3452 here? Note this site doesn't have ifdef support so just include it unconditionally.

2024-11-14 16:29 UTC, ekohl commented on _includes/manuals/3.13/1.2_release_notes.md
To be explicit, that's this line:

https://github.com/theforeman/theforeman.org/blob/035e0eab0b9115cfc8b818ad9f85325f44d593d9/_includes/manuals/3.13/1.2_release_notes.md?plain=1#L3

2024-11-14 16:30 UTC, ekohl approved these changes
I'd like to see https://github.com/theforeman/theforeman.org/pull/2196#discussion_r1838770476 resolved before we announce, but the PR in itself is correct.

2024-11-14 16:35 UTC, ColeHiggins2 commented
@ekohl Just updated. Must have missed that comment

2024-11-14 20:46 UTC, merged