adds my talk at cfgmgmtcamp in Berlin to events
theforeman/theforeman.org pull request #722
Opened 2016-10-19 17:03 UTC by dgoetz

I have added my talk at  cfgmgmtcamp in Berlin to events page.

2016-10-20 07:39 UTC, domcleal requested changes

2016-10-20 07:39 UTC, domcleal commented on _data/events.yml
> +  start: 2016-11-15 14:45 CEST
CET, not CEST? Summer time ends in October.

2016-10-21 15:39 UTC, dgoetz commented on _data/events.yml
> +  start: 2016-11-15 14:45 CEST
Thanks, you are completely right.

2016-10-24 07:08 UTC, merged

2016-10-24 07:08 UTC, domcleal commented
Thanks @dgoetz.