Add multi issue example to git message guidelines.
theforeman/theforeman.org pull request #732
Opened 2016-11-08 21:14 UTC by zjhuntin

Just adds a small example to guidelines for this particular situation.

2016-11-08 21:26 UTC, ehelms approved these changes

2016-11-09 08:16 UTC, domcleal requested changes

2016-11-09 08:16 UTC, domcleal commented on handbook.md
> +Fixes #1234,#5678 - Fix content view yum publish bug
Please improve this example by not repeating "Fix" and to be more specific (match the style or simply re-use the previous example).

2016-11-09 08:16 UTC, domcleal commented on handbook.md
> +If the commit that you are adding fixes multiple issues you can follow this example:
"multiple, distinct issues", else they should be marked as duplicates

2016-11-09 08:16 UTC, domcleal commented on handbook.md
> +Fix a problem where content views were not being published if they
Not necessary to include this?

2016-11-29 17:02 UTC, zjhuntin commented
@domcleal Updated, mind taking another look?

2016-11-30 08:09 UTC, domcleal requested changes
Requested changes not made.

2016-11-30 08:09 UTC, domcleal commented on handbook.md
> +Repositories were not being referenced correctly.
As previous comment (https://github.com/theforeman/theforeman.org/pull/732#discussion_r87147507), why include this paragraph? It's not relevant to the example.

2016-11-30 08:09 UTC, domcleal commented on handbook.md
> +Fixes #1234,#5678 - Content view yum publish bug
Again, please use the existing example.

2016-12-05 19:44 UTC, zjhuntin commented
@domcleal I think this follows the previous example now.

2016-12-06 08:15 UTC, merged

2016-12-06 08:15 UTC, domcleal commented
Merged, thanks.