Added warning about parser limitations
theforeman/theforeman.org pull request #744
Opened 2016-11-16 12:41 UTC by lzap

2016-11-16 12:46 UTC, domcleal requested changes

2016-11-16 12:46 UTC, domcleal commented on _includes/manuals/1.13/4.3.4.2_isc_dhcp.md
> +At the moment, foreman proxy does not recognize all configuration syntax and
"foreman proxy" => "Smart Proxy" as used in this doc

2016-11-16 12:46 UTC, domcleal commented on _includes/manuals/1.13/4.3.4.2_isc_dhcp.md
> +domain-name-servers and range options. These must not be enclosed in pool
Use backticks around routers, d-n-s, range, and pool to indicate they're config directives.

2016-11-16 12:46 UTC, domcleal commented on _includes/manuals/1.13/4.3.4.2_isc_dhcp.md
> +blocks as these are ignored by proxy's config parser.
"the proxy's" or "the Smart Proxy's"

2016-12-09 12:36 UTC, lzap commented
All done, added tested workaround.

2016-12-12 08:24 UTC, domcleal commented
Is this only applicable to 1.13? Is it fixed by #16079? If not, please add to the 1.14 docs too.

2016-12-13 15:55 UTC, lzap commented
Applicable to both, added.

2016-12-14 12:43 UTC, domcleal commented
Sorry, I've just re-read the commit and looked at the test (https://github.com/theforeman/smart-proxy/pull/474/files#diff-0c16be9e3188140992c2d2092eda3f3d), shouldn't that have fixed it? In which case this is only applicable to 1.13.

2016-12-14 14:57 UTC, lzap commented
Yeah you're right, rebased.

2016-12-14 14:57 UTC, domcleal approved these changes

2016-12-14 14:58 UTC, merged

2016-12-14 14:58 UTC, domcleal commented
Merged, thanks @lzap.