Fixes version numbers in katello
theforeman/theforeman.org pull request #749
Opened 2016-11-21 22:53 UTC by johnpmitsch

Many links are broken because we aren't using the variables from the `page` instead of the `site`

2016-11-22 13:54 UTC, ehelms requested changes

2016-11-22 13:54 UTC, ehelms commented on plugins/katello/2.4/cli/index.md
> +foreman_version: 1.13
This should be 2.4 and 1.9 for the katello and foreman versions respectfully.

2016-11-22 13:54 UTC, ehelms commented on plugins/katello/2.4/cli/index.md
> +foreman_version: 1.13
Err sorry, 1.10 of Foreman

2016-11-22 13:54 UTC, ehelms commented on plugins/katello/2.4/installation/index.md
> +foreman_version: "1.10"
Why does this change end up being necessary?

2016-11-22 13:54 UTC, ehelms commented on plugins/katello/3.1/cli/index.md
> +foreman_version: 1.13
Looks like this should be 3.1 and 1.12

2016-11-22 13:55 UTC, johnpmitsch commented on plugins/katello/2.4/installation/index.md
> +foreman_version: "1.10"
it will show as `1.1` where its used in the page

2016-11-23 14:22 UTC, johnpmitsch commented
@ehelms updated

2016-11-23 15:19 UTC, ehelms approved these changes

2016-11-23 15:20 UTC, ehelms commented
@johnpmitsch looks good! Maybe @stbenjam can merge this update for us

2016-11-23 15:47 UTC, stbenjam commented
Looks good, thanks!

2016-11-23 15:47 UTC, merged