fixes #17469 - add apipie-bindings examples to the API docs
theforeman/theforeman.org pull request #754
Opened 2016-11-24 13:28 UTC by evgeni

2016-11-24 20:21 UTC, mmoll requested changes

2016-11-24 20:21 UTC, mmoll commented on _includes/manuals/1.13/5.1.9_apipie-bindings.md
> +```$ vim domains.rb```
IMHO uneeded

2016-11-27 09:17 UTC, evgeni commented on _includes/manuals/1.13/5.1.9_apipie-bindings.md
> +```$ vim domains.rb```
the vim line? ack

2016-11-27 09:18 UTC, evgeni commented
given that the 1.14 manual has been started, should I move this there?

2016-11-27 11:59 UTC, mmoll commented
Copy it there, rather, we want this in both versions. :)

2016-11-27 12:06 UTC, evgeni commented
ack, done :)

2016-11-27 12:15 UTC, merged

2016-11-27 12:16 UTC, mmoll commented
merged, спасибо Женя!