[WIP]Fixes #17614 - Update nightly docs from capsule to smart proxy
theforeman/theforeman.org pull request #769
Opened 2016-12-08 17:31 UTC by zjhuntin

This should only be merged after we branch Katello next, and we have the changes renaming all mentions of Capsule to Proxy or Smart proxy.

2016-12-14 19:29 UTC, ehelms requested changes

2016-12-14 19:29 UTC, ehelms commented on plugins/katello/nightly/installation/smart_proxy.md
> +yum install -y katello-capsule
This got changed to foreman-proxy-content

2016-12-14 19:29 UTC, ehelms commented on plugins/katello/nightly/installation/smart_proxy.md
> +Once you get the repositories configured, install the katello-capsule package on the smart proxy
This got changed to foreman-proxy-content

2016-12-14 20:31 UTC, zjhuntin commented
@ehelms Updated!

2016-12-14 20:58 UTC, ehelms approved these changes

2016-12-14 20:59 UTC, ehelms commented
Thanks @zjhuntin !

2016-12-14 21:01 UTC, ehelms commented
Actually, @zjhuntin , I spoke too soon, I forgot about this guy: https://github.com/theforeman/theforeman.org/blob/gh-pages/_includes/plugins/katello/sidebar.html

Which you may notice has Capsule in it but is also shared amongst Katello versions currently. I think we will want to split that up so we have a version per Katello version and include that appropriately.

2016-12-14 21:02 UTC, zjhuntin commented
@ehelms okay, I'll get working on it

2016-12-14 21:48 UTC, zjhuntin commented
@ehelms Okay, I got it to work doing it this way.

2016-12-15 13:55 UTC, ehelms commented on _layouts/plugins/katello/guide.html
> +---
Where is this file used at?

2016-12-15 14:49 UTC, ehelms commented on plugins/katello/nightly/user_guide/smart_proxies/index.md
> +## How do Smart proxies differ from Smart Proxies?
This title no longer makes sense -- how about `## What is a Foreman Proxy with Content?`

2016-12-15 15:31 UTC, zjhuntin commented on plugins/katello/nightly/user_guide/smart_proxies/index.md
> +## How do Smart proxies differ from Smart Proxies?
I had a good laugh at this.

2016-12-15 15:51 UTC, ehelms requested changes
I found Capsule here -- https://github.com/theforeman/theforeman.org/pull/769/files#diff-65c3065680a6bc8af4a60ebb811402f3R72

I think it should be 'Smart Proxy' everywhere we talk about it sense we treat it as a proper noun.

2016-12-15 16:12 UTC, zjhuntin commented
@ehelms made sure all instances of Smart Proxy are treated as a proper noun.

2016-12-15 17:03 UTC, ehelms commented
Looks good - thanks @zjhuntin !

2016-12-15 17:03 UTC, ehelms approved these changes

2016-12-15 17:04 UTC, merged