LDAP & taxonomies link
theforeman/theforeman.org pull request #771
Opened 2016-12-09 10:15 UTC by dLobatog

To be fair it's a very short explanation - I think the feature is quite simple, and might be biased as I wrote it. If anything about it is confusing and you want me to write anything more about it let me know.

2016-12-12 08:16 UTC, domcleal requested changes

2016-12-12 08:16 UTC, domcleal commented on _includes/manuals/1.14/4.1.1_authentication.md
> +If organizations or locations are enabled, you can assign multiple organizations or locations to your LDAP authentication sources. This will scope users that are automatically created to the set of o
s/scope/assign/, and emphasise that it's only when they're created (IIRC).

2016-12-14 09:26 UTC, dLobatog commented
Updated - thanks @domcleal for reviewing

2016-12-14 09:34 UTC, domcleal approved these changes

2016-12-14 09:34 UTC, merged

2016-12-14 09:34 UTC, domcleal commented
Thanks @dLobatog, merged.