Update partition tables documentation
theforeman/theforeman.org pull request #772
Opened 2016-12-12 08:46 UTC by Klaas-

* explain how dynamic partition tables work
* change Dynamic Partition tables section to Per-Host Partition tables

2016-12-12 09:05 UTC, domcleal requested changes
Generally good, perhaps consider including a very small/trivial example of a dynamic script to show the placement of the comment and the sort of thing that can be done. (i.e. content from http://projects.theforeman.org/projects/foreman/wiki/Dynamic_disk_partitioning).

2016-12-12 09:05 UTC, domcleal commented on _includes/manuals/1.14/4.4.4_prov_ptables.md
> +Some operating systems allow you to create partition tables via scripts. At the moment Kickstart and AutoYaST based systems can use this feature. Partition templates starting with #Dynamic are interp
Use backticks around `#Dynamic` and `@dynamic` so it's clear that it's literal.

2016-12-12 09:05 UTC, domcleal commented on _includes/manuals/1.14/4.4.4_prov_ptables.md
> +Kickstart will run dynamic partition tables as a pre-install bash script. This script needs to create a complete Kickstart partition table in '/tmp/diskpart.cfg'. This partition table will then be re
1. "as a pre-install bash script using a %pre scriplet."
1. ".. read by anaconda for the installation by using `%include /tmp/diskpart.cfg`." (to show it's not automatic)

2016-12-12 14:56 UTC, Klaas- commented
Okay, I added examples and enhanced the wording, squash on commit please if there are no other suggestions

2016-12-12 15:03 UTC, domcleal requested changes

2016-12-12 15:03 UTC, domcleal commented on _includes/manuals/1.14/4.4.4_prov_ptables.md
> +AutoYaST will run dynamic partition tables as a pre-install bash script. This script needs to create a AutoYaST XML file in ```/tmp/profile/modified.xml```. The modified.xml file will be read by YaST
1. "tamplates" -> "templates"
1. Not sure the line about this being a suggestion is necessary.
1. "disklayout_lvm.erb" is an internal filename within the codebase, I don't think it's helpful to reference it. Either use the name or remove that comment.

2016-12-12 15:03 UTC, domcleal commented on _includes/manuals/1.14/4.4.4_prov_ptables.md
> +      <device>/dev/vg00</device>
Can you reduce the size of this example? My point was that it should be a small or very trivial example that's a few lines long, not a complete piece of code if possible - this is very large.

The points it should get across are:

1. `#Dynamic` header
1. Generate the modified file.

You could probably delete this second device and many of the separate partitions.

2016-12-12 15:22 UTC, Klaas- commented on _includes/manuals/1.14/4.4.4_prov_ptables.md
> +      <device>/dev/vg00</device>
this is the default community-templates example for an lvm host, but yeah I can make it shorter

2016-12-12 15:24 UTC, Klaas- commented on _includes/manuals/1.14/4.4.4_prov_ptables.md
> +AutoYaST will run dynamic partition tables as a pre-install bash script. This script needs to create a AutoYaST XML file in ```/tmp/profile/modified.xml```. The modified.xml file will be read by YaST
Will fix typo and change to name of that template

2016-12-12 15:25 UTC, Klaas- commented on _includes/manuals/1.14/4.4.4_prov_ptables.md
> +AutoYaST will run dynamic partition tables as a pre-install bash script. This script needs to create a AutoYaST XML file in ```/tmp/profile/modified.xml```. The modified.xml file will be read by YaST
and that line about the suggestion - I wanted to make clear that its an xml document, so it doesn't matter where you include the section :)

2016-12-12 15:32 UTC, domcleal commented on _includes/manuals/1.14/4.4.4_prov_ptables.md
> +      <device>/dev/vg00</device>
Yeah, no need to have the entire default here. If a user needs the default, it's in their installation.

2016-12-13 12:47 UTC, Klaas- commented
@domcleal is this acceptable?

2016-12-13 12:48 UTC, domcleal approved these changes

2016-12-13 12:49 UTC, merged

2016-12-13 12:49 UTC, domcleal commented
Merged, thank you @Klaas-.