Specify RHEL repos to install before agent
theforeman/theforeman.org pull request #785
Opened 2016-12-29 08:32 UTC by dLobatog

The agent will not install in RHEL without the optional and extras
repos, with errors such as
https://gist.github.com/dLobatog/f9d3751861d0a1d1045f4831f3d7dca9

This commit adds that information to the installation and upgrade of the
latest versions

2016-12-29 08:41 UTC, dLobatog commented
Hmm... doesn't seem like this is enough, I tried on a new host and EPEL is the key

```

=======================================================================================================================================
 Package                        Arch        Version                  Repository                                                   Size
=======================================================================================================================================
Installing:
 katello-agent                  noarch      2.7.0-1.el7              centos7-devel-lobacorp_katello_client_night_el7_x86_64       26 k
Installing for dependencies:
 gofer                          noarch      2.7.6-1.el7              centos7-devel-lobacorp_katello_client_night_el7_x86_64       84 k
 katello-agent-fact-plugin      noarch      2.7.0-1.el7              centos7-devel-lobacorp_katello_client_night_el7_x86_64       10 k
 pulp-rpm-handlers              noarch      2.10.0-1.el7             centos7-devel-lobacorp_katello_client_night_el7_x86_64       73 k
 python-gofer                   noarch      2.7.6-1.el7              centos7-devel-lobacorp_katello_client_night_el7_x86_64      132 k
 python-gofer-proton            noarch      2.7.6-1.el7              centos7-devel-lobacorp_katello_client_night_el7_x86_64       53 k
 python-isodate                 noarch      0.5.0-4.pulp.el7         centos7-devel-lobacorp_katello_client_night_el7_x86_64       50 k
 python-pulp-agent-lib          noarch      2.10.0-1.el7             centos7-devel-lobacorp_katello_client_night_el7_x86_64       91 k
 python-pulp-common             noarch      2.10.0-1.el7             centos7-devel-lobacorp_katello_client_night_el7_x86_64      123 k
 python-pulp-rpm-common         noarch      2.10.0-1.el7             centos7-devel-lobacorp_katello_client_night_el7_x86_64       66 k
 python-qpid-proton             x86_64      0.14.0-1.el7             epel                                                        212 k
 qpid-proton-c                  x86_64      0.14.0-1.el7             epel                                                        129 k

Transaction Summary
=======================================================================================================================================
Install  1 Package (+11 Dependent packages)
```

Can anyone else confirm it?

2017-01-09 15:59 UTC, ehelms commented
EPEL is required to install this for EL.

2017-01-09 20:43 UTC, dLobatog commented
@ehelms Alright - extras and optional are not necessary then? Should I add a section like https://github.com/theforeman/theforeman.org/pull/774 for katello-client?

2017-01-09 22:53 UTC, ehelms commented
A section? or just adding EPEL to these katello client instructions?

2017-01-10 13:01 UTC, dLobatog commented
Yeah sorry, just adding EPEL to the katello-client instructions. The question is, should I remove extras and optional from there too?

2017-01-10 14:06 UTC, jlsherrill commented
extras and optional shouldn't be needed, so i would remove

2017-01-10 19:36 UTC, dLobatog commented
Updated to ask for EPEL on 3.1, 3.2, 3.3 and nightly.

I didn't update the EL6 installation instructions as they ask to use '
wget https://copr.fedoraproject.org/coprs/dgoodwin/subscription-manager/repo/epel-6/dgoodwin-subscription-manager-epel-6.repo -O /etc/yum.repos.d/dgoodwin-subscription-manager-epel-6.repo' - I suppose that works too, but I don't really know why that's needed vs the regular EPEL.

2017-01-19 20:13 UTC, dLobatog commented
@jlsherrill or @ehelms mind to take another look?

2017-01-19 20:21 UTC, ehelms requested changes
That repository on EL6 is for subscription-manager only since its not available otherwise. Users would still need EPEL if you want to update.

2017-01-19 20:21 UTC, ehelms commented on plugins/katello/nightly/upgrade/clients.md
> +     <option value="el7">Enterprise Linux 7 (RHEL7, CentOS, etc.)</option>
I think this could just be `RHEL` (since the 5,6,7 is implied by the previous part)

2017-01-20 08:40 UTC, dLobatog commented
@ehelms Updated according to what you said:

* EL6 also contains EPEL instructions now
* Removed the RHEL number from the parentheses next to "Enterprise Linux X".

2017-01-20 14:02 UTC, ehelms approved these changes

2017-01-20 14:03 UTC, ehelms commented
Thanks @dLobatog !

2017-01-20 14:03 UTC, merged