Puppet 4.4+ environment_classes in auth.conf
theforeman/theforeman.org pull request #786
Opened 2016-12-30 08:41 UTC by dLobatog

Puppet versions 4.4 and newer need a section to allow
environment_classes in auth.conf.

Adding these rules here will not be a problem for people using Puppet older than 4.4, as those paths will not resolve to anything. For people who use newer Puppet versions, it will allow them to import classes.

2017-01-03 08:05 UTC, domcleal requested changes

2017-01-03 08:05 UTC, domcleal commented on _includes/manuals/1.13/4.3.6_smartproxy_puppet.md
> +path /puppet/v3/environment_classes
Unsure if this is applicable to 1.13, isn't this only used on 1.14?

2017-01-03 11:34 UTC, dLobatog commented on _includes/manuals/1.13/4.3.6_smartproxy_puppet.md
> +path /puppet/v3/environment_classes
Correct - I'll change it

2017-01-03 11:35 UTC, dLobatog commented
@domcleal Updated to remove the changes in 1.13 as the proxy doesn't call v3/environment_classes in that version, thanks for taking a look

2017-01-03 12:02 UTC, domcleal requested changes

2017-01-03 12:02 UTC, domcleal commented on _includes/manuals/1.14/4.3.6_smartproxy_puppet.md
> +      }
Could you fix the indentation to match the other blocks here, and lines 82/83? (remove 3 leading spaces)

2017-01-03 16:08 UTC, dLobatog commented
@domcleal Updated to remove the leading spaces, sorry!

2017-01-04 08:27 UTC, domcleal approved these changes

2017-01-04 08:27 UTC, merged

2017-01-04 08:28 UTC, domcleal commented
Merged, thanks @dLobatog.