Update openscap docs - tailoring files
theforeman/theforeman.org pull request #799
Opened 2017-01-11 10:20 UTC by xprazak2

2017-01-11 16:37 UTC, ares requested changes
except one nit looks good, grammar check by other reviewer would be appreciated

2017-01-11 16:37 UTC, ares commented on plugins/foreman_openscap/0.6/index.md
> +There are three basic concepts (entities) in OpenSCAP plug-in: SCAP Contents, Compliance Policies, ARF Reports and Tailoring Files.
s/three/four/

2017-01-12 07:09 UTC, xprazak2 commented
I updated the number of components

2017-01-12 12:04 UTC, ares approved these changes

2017-01-17 13:20 UTC, merged

2017-01-17 13:20 UTC, mmoll commented
merged, díky @xprazak2!