Show old version warning on quickstart pages
theforeman/theforeman.org pull request #811
Opened 2017-02-04 10:49 UTC by dLobatog

I found a user today which was using a very old version of Foreman. The reason is that when you google for terms like "foreman install" , "quick install foreman", etc.. on any search engine, the top results are for old versions. For example:

https://duckduckgo.com/?q=quick+install+foreman&t=ffab&ia=web
https://encrypted.google.com/search?hl=en&q=quick%20install%20foreman

2017-02-04 18:19 UTC, mmoll approved these changes

2017-02-08 08:22 UTC, domcleal requested changes

2017-02-08 08:22 UTC, domcleal commented on _layouts/quickstart.html
> +				<p style="margin-bottom: 0">This manual is for Foreman {{ page.version }}, but the <a href="{{ site.baseurl }}manuals/{{ layout.latestversion }}/index.html">latest version is {{ layout.latestvers
Nitpick, you use "This quickstart" on line 22 but "This manual" here, it should be the same.

2017-02-08 08:22 UTC, domcleal commented on _layouts/quickstart.html
> +    <div id="doc" class="col-md-12">
Indentation's off, probably should use tabs to match the rest.

2017-02-08 08:22 UTC, domcleal commented on _layouts/quickstart.html
> +	  <div class="row">
mixed tabs/spaces

2017-02-08 22:00 UTC, dLobatog commented
@domcleal Thanks - updated to use tabs & "This quickstart guide" consistently

2017-02-09 08:26 UTC, domcleal requested changes
The file manuals/1.14/quickstart_guide.md is still using the `manual` layout and also needs updating to `quickstart`.

2017-02-09 15:21 UTC, dLobatog commented
@domcleal Updated 1.14 quickstart_guide to 'quickstart' layout - slipped under my radar, thanks

2017-02-09 15:24 UTC, domcleal approved these changes

2017-02-09 15:25 UTC, merged

2017-02-09 15:25 UTC, domcleal commented
Merged, thanks @dLobatog.