Update puppet master API info
theforeman/theforeman.org pull request #814
Opened 2017-02-13 11:25 UTC by ares

My observations from what I read in code.

2017-02-13 11:32 UTC, domcleal requested changes

2017-02-13 11:32 UTC, domcleal commented on _includes/manuals/1.14/4.3.6_smartproxy_puppet.md
> +* On Puppet 4, the smart proxy will use the environments and environment_classes Puppet Server APIs to list classes and parameters. If you're running Puppet Master or Puppet Server older than 4.4, th
1. "the environments and environment_classes Puppet Server APIs" should state that it uses environment_classes _or_ resource_types, not only environment_classes.
1. Simply state that the environment_classes API is available and used on Puppet 4.4 or higher, and resource_types on 4.0 to 4.3.
1. I don't think the recommendation to set a different Puppet version to the running version belongs in the manual.

2017-02-14 16:33 UTC, ares commented on _includes/manuals/1.14/4.3.6_smartproxy_puppet.md
> +* On Puppet 4, the smart proxy will use the environments and environment_classes Puppet Server APIs to list classes and parameters. If you're running Puppet Master or Puppet Server older than 4.4, th
environment_classes is only available on puppet server, while resource_types is also on puppet master (afaiu the difference) which is why I tried to put the info there, anyway I simplified it as suggested, please take another look

2017-02-15 08:12 UTC, merged

2017-02-15 08:12 UTC, domcleal commented
Merged, thanks @ares/