Added CVE-2016-9593
theforeman/theforeman.org pull request #824
Opened 2017-03-06 14:53 UTC by lzap

2017-03-06 14:57 UTC, domcleal requested changes

2017-03-06 14:57 UTC, domcleal commented on security.md
> +It was found that foreman-debug did not obfuscate sensitive information (such as passwords) from the katello-installer log file, allowing a user authorized to access the log files created by foreman-
1. foreman-installer
1. Also answer and other configuration files, not only log files.
1. "the log files created by foreman-debug" should be "archives created by foreman-debug".

2017-03-06 14:57 UTC, domcleal commented on security.md
> +* Affects all Foreman versions up to 1.14.x
1.2.0 up to and including 1.14.x

2017-03-06 14:57 UTC, domcleal commented on security.md
> +* Fix released in Foreman 1.15.0
Fix is pending release

2017-03-06 15:08 UTC, lzap commented
Done.

2017-03-06 15:10 UTC, domcleal requested changes

2017-03-06 15:10 UTC, domcleal commented on security.md
> +* Fix is pending release Foreman 1.15.0
"pending release _in_ Foreman [..]", or just "pending release"

2017-03-08 14:21 UTC, lzap commented on security.md
> +* Fix is pending release Foreman 1.15.0
Fixed.

2017-03-08 14:22 UTC, merged

2017-03-08 14:22 UTC, domcleal commented
Merged, thanks.