Add openscap doc for report downloads and running scans from UI
theforeman/theforeman.org pull request #829
Opened 2017-03-14 10:36 UTC by xprazak2

2017-03-15 08:59 UTC, ares requested changes
one nit otherwise big :+1:

2017-03-15 08:59 UTC, ares commented on plugins/foreman_openscap/0.6/index.md
> +## 4.5 Tailoring files ( foreman_openscap >= 0.6.5 )
:clap:

2017-03-15 08:59 UTC, ares commented on plugins/foreman_openscap/0.6/index.md
> +In version 0.6.5 and higher, you can initiate scans from UI. Simply go to hosts page and select "Run OpenSCAP scan" from the dropdown menu. This will initiate a scan for all policies that are assigne
> foreman_remote_execution plugin needs to be installed

maybe mentioning the version would be useful, it's currently in master only but next rex version should be 1.2.3, I kindly ask @adamruzicka to confirm the next version number

2017-03-15 11:45 UTC, adamruzicka commented on plugins/foreman_openscap/0.6/index.md
> +In version 0.6.5 and higher, you can initiate scans from UI. Simply go to hosts page and select "Run OpenSCAP scan" from the dropdown menu. This will initiate a scan for all policies that are assigne
Yup, the next REX release will be 1.2.3 and will contain the needed features.

2017-03-16 10:59 UTC, xprazak2 commented
I added the needed rex version,

2017-03-16 12:10 UTC, ares approved these changes

2017-03-16 12:11 UTC, ares commented
Thank you @xprazak2, merging!

2017-03-16 12:11 UTC, merged