Add foreman_templates manual
theforeman/theforeman.org pull request #852
Opened 2017-04-10 13:52 UTC by ares

2017-04-11 08:48 UTC, GregSutcliffe requested changes
Looks pretty good to me, thanks @ares! A few small typos and wording changes, that's all.

2017-04-11 08:48 UTC, GregSutcliffe commented on plugins/foreman_templates/4.0/index.md
> +This plugin enables synchronization of provisioning templates, partition tables, job templates from external git repository and/or file system. It can be used both with the [community templates](http
"*and* job templates" will finish the list correctly, otherwise it's dangling

2017-04-11 08:48 UTC, GregSutcliffe commented on plugins/foreman_templates/4.0/index.md
> +You can use the native git support for simple syncrhonization with remote git repositories, which is usually useful for syncing new template versions from community repository or for exporting local
I think "use this plugin to sync the directory when required." might read better here, but it's minor.

2017-04-11 08:48 UTC, GregSutcliffe commented on plugins/foreman_templates/4.0/index.md
> +
No mention of install from packages here? IMO it's preferable to using the installer, but I know I'm in a minority :)

2017-04-11 08:48 UTC, GregSutcliffe commented on plugins/foreman_templates/4.0/index.md
> +    <td colspan="2">git branch to read or write from/to (only for git url), default value is based on current Foreman version - e.g. develop or 1.15-stable</td>
I'd say "only for git-based repositories" in the parentheses, and maybe put the "repo" option immediately before this one so it's easily referenced.

2017-04-11 08:48 UTC, GregSutcliffe commented on plugins/foreman_templates/4.0/index.md
> +<table class="table table-bordered table-condensed table-striped">
I see you're going for alphabetical setting order - but many options are rarely used, does it makes sense to put common options first?

2017-04-11 08:48 UTC, GregSutcliffe commented on plugins/foreman_templates/4.0/index.md
> +Both importing and exporting is available as rake tasks. Rake tasks are triggered from terminal. If you installed the plugin using foreman-installer, or simply it's package based installation), you s
Package install mentioned here, so it should definitely go under Installation too (see earlier comment)

2017-04-11 08:48 UTC, GregSutcliffe commented on plugins/foreman_templates/4.0/index.md
> +Both importing and exporting is available as rake tasks. Rake tasks are triggered from terminal. If you installed the plugin using foreman-installer, or simply it's package based installation), you s
s/If you installed Foreman alternatively, e.g. cloned from git, you should likely use/Source-based installs of Foreman will need to use Bundler to call Rake as normal, e.g./

2017-04-11 08:48 UTC, GregSutcliffe commented on plugins/foreman_templates/4.0/index.md
> +Both importing and exporting is available as rake tasks. Rake tasks are triggered from terminal. If you installed the plugin using foreman-installer, or simply it's package based installation), you s
I'd put the API sentence on a new line/paragraph to make it stand out for those who want to know.

2017-04-11 08:48 UTC, GregSutcliffe commented on plugins/foreman_templates/4.0/index.md
> +The example above would clone the repository to some temp directory. If `branch` was specified, it checkouts this git branch. Then if `dirname` was provided, it will "cd" into it. Finally is searches
s/it checkouts this git branch/it switches to this branch/

2017-04-11 08:48 UTC, GregSutcliffe commented on plugins/foreman_templates/4.0/index.md
> +The example above would clone the repository to some temp directory. If `branch` was specified, it checkouts this git branch. Then if `dirname` was provided, it will "cd" into it. Finally is searches
s/Finally is/Finally it/

2017-04-11 08:48 UTC, GregSutcliffe commented on plugins/foreman_templates/4.0/index.md
> +The parsing process reads the content of the file. It expects the content of the template including a metadata. The metadata are an ERB comment on top of the file. It's in yaml format and specifies t
"including a metadata block." or "including some template metadata" - your choice :)

2017-04-11 08:48 UTC, GregSutcliffe commented on plugins/foreman_templates/4.0/index.md
> +The parsing process reads the content of the file. It expects the content of the template including a metadata. The metadata are an ERB comment on top of the file. It's in yaml format and specifies t
Is it worth linking to an example from community-templates to show a metadata block?

2017-04-12 14:26 UTC, ares commented on plugins/foreman_templates/4.0/index.md
> +<table class="table table-bordered table-condensed table-striped">
This is also the order we have in settings table. It's not a huge number so I'd keep it ordered alphabetical

2017-04-12 14:33 UTC, sean797 requested changes

2017-04-12 14:33 UTC, sean797 commented on plugins/foreman_templates/4.0/index.md
> +This plugin enables synchronization of provisioning templates, partition tables, job templates from external git repository and/or file system. It can be used both with the [community templates](http
Does it require the same directory structure? I thought it worked with the metadata and all files needed to be suffixed with `.erb`

2017-04-12 14:33 UTC, sean797 commented on plugins/foreman_templates/4.0/index.md
> +This task based on $repo setting either uses git or scans local directory for templates to import. If you want to customize any of setting for a particular run, just specify it as extra argument.
s/If you want to customize any of setting/If you want to customize any setting/

I'm not sure `of` makes sense here.

2017-04-12 14:33 UTC, sean797 commented on plugins/foreman_templates/4.0/index.md
> +foreman-rake templates:import prefix='[community] '
Not required but it might be nice to show something like:

```sh
$ tree /tmp/my-repo/
/tmp/my-repo/
└── large-ptable.erb

0 directories, 1 file
$ foreman-rake templates:import repo=/tmp/my-repo/ prefix='[community] '
```
Would result in a template named `[community] large-ptable`.

2017-04-12 14:33 UTC, sean797 commented on plugins/foreman_templates/4.0/index.md
> +If the `repo` is git repository, we clone it to some temp directory. Then we apply changes to template files and if there was a change, we automatically create a commit with generate message and push
s/Then we apply changes to template files and if there was a change, we automatically create a commit with generate message and push it back to origin./Then we apply changes to template files and automatically create a commit with a generate message and push it back to origin./

Also

s/clone it to some temp directory/clone it to a temp directory/

Also

s/To specify local directory/To specify a local directory/

2017-04-12 14:40 UTC, ares commented
Thanks @GregSutcliffe, I think I addressed all your comments. Please take another look.

@sean797 same for you. Just one answer instead of a text change

> Does it require the same directory structure? I thought it worked with the metadata and all files needed to be suffixed with .erb

It does not required the same structure and it works as you said for import. But export creates the same structure the community-templates has, so if you want to use both direction sync, you should use this structure.

2017-04-12 14:40 UTC, ares commented on plugins/foreman_templates/4.0/index.md
> +foreman-rake templates:import prefix='[community] '
added as a new example with a comment

2017-04-13 07:58 UTC, sean797 approved these changes
LGTM @ares ! Thanks for doing this 👍

2017-04-13 10:55 UTC, GregSutcliffe commented on plugins/foreman_templates/4.0/index.md
> +<table class="table table-bordered table-condensed table-striped">
We'll have to agree to disagree on this, as I feel for docs the user should get the most relevant info first - but I don't feel strongly enough to insist on it :)

2017-04-13 11:01 UTC, GregSutcliffe commented on plugins/foreman_templates/4.0/index.md
> +If you installed the plugin using package directly, you should run the migrations and seed (just to be sure) and restart the Foreman.
Can we either detail these steps or link to where they can be found? If this is the first plugin a user ever installs, they may not know how...

2017-04-13 11:02 UTC, GregSutcliffe commented on plugins/foreman_templates/4.0/index.md
> +Few more useful examples follow
nitpick: *A* few more ...

2017-04-13 11:04 UTC, GregSutcliffe commented on plugins/foreman_templates/4.0/index.md
> +* foreman_templates plugin [https://github.com/theforeman/foreman_chef](https://github.com/theforeman/foreman_templates)
Url is right, but text says Chef :P

2017-04-13 11:05 UTC, GregSutcliffe commented
@ares Almost there, a couple of tiny things :)

2017-04-13 13:39 UTC, ares commented on plugins/foreman_templates/4.0/index.md
> +If you installed the plugin using package directly, you should run the migrations and seed (just to be sure) and restart the Foreman.
I would prefer not documenting it in details. foreman-installer is the recommended way. We also don't document you could do `git clone ...`

2017-04-13 13:40 UTC, ares commented on plugins/foreman_templates/4.0/index.md
> +* foreman_templates plugin [https://github.com/theforeman/foreman_chef](https://github.com/theforeman/foreman_templates)
damn, I swear I grepped it :-)

2017-04-13 13:41 UTC, ares commented
@GregSutcliffe thanks, another round? :-)

2017-04-13 13:45 UTC, GregSutcliffe commented on plugins/foreman_templates/4.0/index.md
> +If you installed the plugin using package directly, you should run the migrations and seed (just to be sure) and restart the Foreman.
I don't think we need details (they go out of date) but maybe a link to https://theforeman.org/plugins/#2.2Packageinstallation ?

2017-04-13 13:48 UTC, GregSutcliffe approved these changes

2017-04-13 13:48 UTC, merged

2017-04-13 13:48 UTC, GregSutcliffe commented
Merged, thanks @ares!