New proxy realm provider config for 1.15
theforeman/theforeman.org pull request #856
Opened 2017-04-18 09:00 UTC by dLobatog

2017-04-18 09:12 UTC, domcleal requested changes

2017-04-18 09:12 UTC, domcleal commented on _includes/manuals/1.15/4.3.8_smartproxy_realm.md
>  :realm_provider: freeipa
1. `:use_provider`
1. `realm_freeipa`

2017-04-18 09:12 UTC, domcleal commented on _includes/manuals/1.15/4.3.8_smartproxy_realm.md
> +We have a provider for `freeipa` available. The configuration for each provider should be
1. Avoid pronouns - perhaps use the same format (a bullet point list) as other sections (DNS, DHCP) with provider support.
1. It's the `realm_freeipa` provider, or it's _for FreeIPA_, or both. This should probably read: "`realm_freeipa` - host object management in FreeIPA"

2017-04-18 09:12 UTC, domcleal commented on _includes/manuals/1.15/4.3.8_smartproxy_realm.md
> +:keytab: /etc/foreman-proxy/freeipa.keytab
`keytab_path`

2017-04-18 09:12 UTC, domcleal commented on _includes/manuals/1.15/4.3.8.2_freeipa_realm.md
>  If you're using FreeIPA to manage DNS records, and want them to be automatically deleted when the host is deleted in Foreman, set this to true:
Line below this should be merely `:remove_dns: true`.

2017-04-18 09:12 UTC, domcleal commented on _includes/manuals/1.15/4.3.8_smartproxy_realm.md
> +On `realm_freeipa.yml`:
s/on/in/

2017-04-18 10:35 UTC, dLobatog commented
Updated, thanks @domcleal

2017-04-18 10:48 UTC, domcleal requested changes

2017-04-18 10:48 UTC, domcleal commented on _includes/manuals/1.15/4.3.8_smartproxy_realm.md
> +* 'realm_freeipa' -  host object management in FreeIPA
Use backticks for code formatting.

2017-04-19 14:15 UTC, dLobatog commented
Updated now with backticks on `realm_freeipa`

2017-04-20 07:29 UTC, domcleal approved these changes

2017-04-20 07:29 UTC, merged

2017-04-20 07:29 UTC, domcleal commented
Thanks @dLobatog.