Add blog post on creating ubuntu repos in katello.
theforeman/theforeman.org pull request #872
Opened 2017-05-19 10:20 UTC by lfisher47

2017-05-19 13:41 UTC, GregSutcliffe commented
@ekohl @jlsherrill thoughts?

2017-05-19 14:18 UTC, ekohl requested changes

2017-05-19 14:18 UTC, ekohl commented on _posts/2017-05-19-creating-ubuntu-repo-in-katello.md
> +#Building Ubuntu Using Katello File Repo
Looks like Github prefers a space to render it (recurring thing in each header).

2017-05-19 14:18 UTC, ekohl commented on _posts/2017-05-19-creating-ubuntu-repo-in-katello.md
> +I created a script to do this for me. I made the following assumptions:
If you write "which made the following assumptions" you can avoid the use of "I".

2017-05-19 14:18 UTC, ekohl commented on _posts/2017-05-19-creating-ubuntu-repo-in-katello.md
> +I created a product called Ubuntu and made a repository for each Ubuntu Distro I was trying to use. In this case, I have a repo called xenial. The type is file and the url is pointed to the media I h
There's a lot of "I" in this paragraph. I'd suggest to rephrase it a bit.

2017-05-19 14:18 UTC, ekohl commented on _posts/2017-05-19-creating-ubuntu-repo-in-katello.md
> +* Issues:  /var/spool/pulp stores a copy of the files as it syncs, which I did not give enough space to since it was not listed in the katello installer documentation.  Due to this, it takes many man
This could be listed under assumptions.

2017-05-19 14:18 UTC, ekohl commented on _posts/2017-05-19-creating-ubuntu-repo-in-katello.md
> +Update the Ubuntu Mirror Installation media to http://foreman/pulp/isos/Default_Organization-Ubuntu-$release/
Either make it a list or write it as a sentence.

2017-06-15 14:41 UTC, GregSutcliffe commented
@lfisher47 would you like me to fix up the issues mention by @ekohl? Happy to assist in getting this published ;)

2017-06-15 15:10 UTC, lfisher47 commented
Yeah, if you would be willing to do that, that would be great. It's been on
my todo list, but never seems to bubble up.

On Thu, Jun 15, 2017 at 10:41 AM, Greg Sutcliffe <notifications@github.com>
wrote:

> @lfisher47 <https://github.com/lfisher47> would you like me to fix up the
> issues mention by @ekohl <https://github.com/ekohl>? Happy to assist in
> getting this published ;)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/theforeman/theforeman.org/pull/872#issuecomment-308754374>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AELS1Gw2GMfVAGC9S4vHNnGYAuLVRbO3ks5sEUKdgaJpZM4NgWB0>
> .
>

2017-07-18 12:50 UTC, GregSutcliffe commented
@lfisher47 ugh, doesn't seem to be bubbling up my list either. I'll try to get to it soon. In the meantime, https://groups.google.com/forum/#!msg/foreman-dev/ENbHazmvAGY/YrnN_8M1CwAJ might be interesting to you :)

2018-01-29 11:27 UTC, dLobatog reviewed
@lfisher47 Any updates here?

2018-01-29 11:40 UTC, sean797 commented
Is there much point in this anymore? Considering Katello is going to have deb support in the next release.

2018-05-22 18:09 UTC, beav commented
@lfisher47 I made some of the updates requested by @ekohl.

Re https://github.com/theforeman/theforeman.org/pull/872#issuecomment-361220186, I think the post is still valuable since it is useful for people not on the latest/greatest version. I added that it was on 3.5 (I assumed this but it may not be true). I'll make another small update to say you should just use native deb support if your version has it.

2018-06-19 14:57 UTC, GregSutcliffe commented
@beav good to merge? happy to do so today/tomorrow, it looks good and still useful :)

2018-06-19 17:11 UTC, beav commented
@GregSutcliffe :+1: from me to merge

2018-06-20 14:47 UTC, merged

2018-06-20 14:47 UTC, GregSutcliffe commented
Squashed with a minor change to the intro and date. Thanks all!