Add docs for importing locked templates
theforeman/theforeman.org pull request #883
Opened 2017-05-29 12:32 UTC by xprazak2

2017-05-29 14:03 UTC, ares requested changes

2017-05-29 14:03 UTC, ares commented on plugins/foreman_templates/5.0/index.md
> +Templates shipped by Foreman are now locked. Template import does not update locked templates by default. Ouptut shows the info about which templates were skipped because of lock ("Skipping Template
> Templates shipped by Foreman are now locked

I'd remove `now`, it's locked in last stable release so.

2017-05-29 14:03 UTC, ares commented on plugins/foreman_templates/5.0/index.md
> +The import procedure uses template metadata to determine Organization/Location asssociations. When non-admin user initiates the import via API, it may be possible that metadata do not contain any Org
I'd append "To import such template, update it's metadata so it contains at least one Organization/Location that user is assigned to".

2017-05-29 14:03 UTC, ares commented on plugins/foreman_templates/5.0/index.md
> +When there is OrgA with template some_tmpl and b_user (user only in OrgB) tries to import some_tmpl (which is not yet present in OrgB), it fails with: `name has already been taken`. This is a general
I'd append "To import such template, rename it in it's metadata or associate existing template with the same name in OrgA also to OrgB.

2017-05-30 07:59 UTC, xprazak2 commented
Updated.

2017-05-30 10:24 UTC, ares approved these changes

2017-05-30 10:24 UTC, ares commented
Thanks @xprazak2, merging!

2017-05-30 10:24 UTC, merged