Correct link to all changes in 1.15
theforeman/theforeman.org pull request #886
Opened 2017-06-01 14:49 UTC by tbrisker

2017-06-01 14:55 UTC, ohadlevy requested changes

2017-06-01 14:55 UTC, ohadlevy commented on _includes/manuals/1.15/1.2_release_notes.md
> +*A full list of changes in 1.15.0 is available via [Redmine](http://projects.theforeman.org/projects/foreman/issues?release_id=209)*
this url lists all the open issues left in 1.15...

2017-06-01 15:01 UTC, tbrisker commented on _includes/manuals/1.15/1.2_release_notes.md
> +*A full list of changes in 1.15.0 is available via [Redmine](http://projects.theforeman.org/projects/foreman/issues?release_id=209)*
are you sure? I don't see any open issues there

2017-06-01 15:02 UTC, ohadlevy commented on _includes/manuals/1.15/1.2_release_notes.md
> +*A full list of changes in 1.15.0 is available via [Redmine](http://projects.theforeman.org/projects/foreman/issues?release_id=209)*
@tbrisker I'm sure, there are some cookies in use...

2017-06-01 20:36 UTC, tbrisker commented
Updated, hopefully got the correct link this time.

2017-06-08 12:54 UTC, merged

2017-06-08 12:54 UTC, mmoll commented
merged, thanks @tbrisker!