Add debugging info for foreman_openscap
theforeman/theforeman.org pull request #893
Opened 2017-06-09 08:24 UTC by xprazak2

2017-06-15 11:55 UTC, ares requested changes
Very nice write-up. I left few possibly improving comments.

2017-06-15 11:55 UTC, ares commented on plugins/foreman_openscap/0.7/index.md
> +There will be an entry for each policy that is assigned to your host.
The policy entry starts by number followed by colon. Policy attributes are indented by 2 spaces.

2017-06-15 11:55 UTC, ares commented on plugins/foreman_openscap/0.7/index.md
> +    > foreman_scap_client $policy_id
I'd remove `>`, usually `$` is used for commands that should be executed under normal user, `#` for commands ran under root. In this case I think we can simply remove the character completely.

2017-06-15 11:55 UTC, ares commented on plugins/foreman_openscap/0.7/index.md
> +    > tail -f /var/log/foreman-proxy/proxy.log
I'd remove `>`, usually `$` is used for commands that should be executed under normal user, `#` for commands ran under root. In this case I think we can simply remove the character completely.

2017-06-15 11:55 UTC, ares commented on plugins/foreman_openscap/0.7/index.md
> +Scanning and report generation are based on cron. You can inspect all the cron lines in ```/etc/cron.d/foreman_scap_client_cron```. This file is managed by Puppet and any changes will be overwritten
s/and any changes/and any manual changes/
s/next Puppet run/next Puppet agent run/

2017-06-15 11:55 UTC, ares commented on plugins/foreman_openscap/0.7/index.md
> +Config file for foreman_scap_client is located at ```/etc/foreman_scap_client/config.yaml```. It should look something like this:
This file is also managed by Puppet and any manual changes will be rewritten on next Puppet agent run.

2017-06-19 08:30 UTC, xprazak2 commented
I made changes as suggested.

2017-06-20 11:05 UTC, ares approved these changes

2017-06-20 11:06 UTC, ares commented
Thanks @xprazak2, merging!

2017-06-20 11:06 UTC, merged