Add foreman-docker 3.x version manual
theforeman/theforeman.org pull request #900
Opened 2017-06-27 09:47 UTC by bastilian

including compatibility information

2017-06-28 12:10 UTC, mmoll requested changes

2017-06-28 12:10 UTC, mmoll commented on plugins/foreman_docker/3.x/index.md
> +    # yum install ruby193-rubygem-foreman_docker
that's old :)

2017-06-28 12:10 UTC, mmoll commented on plugins/foreman_docker/3.x/index.md
> +
superfluous newline

2017-06-28 12:10 UTC, mmoll commented on plugins/foreman_docker/3.x/index.md
> +**Note:* API v2 as default and v1 to fall back on.
API v2 is default, v1 is used as fallback

2017-06-28 12:10 UTC, mmoll commented on plugins/foreman_docker/3.x/index.md
> +Set up the repo as explained in the link above, then run
which link? 😖

2017-06-28 12:10 UTC, mmoll commented on plugins/foreman_docker/3.x/index.md
> +**Procedure 1.1. To Prepare a Docker Host:**
Is there the possibility to use `####` as headlining here with the current github-pages markdown? But I'm unsure if that's more or less confusing than the current "inline" numbering.

2017-06-28 12:30 UTC, mmoll commented on plugins/foreman_docker/3.x/index.md
> +Follow the Katello [Docker documentation](http://www.katello.org/docs/user_guide/docker/docker.html).
404

2017-07-10 13:37 UTC, bastilian commented
@mmoll Thanks for reviewing! I've updated it and addressed the issues and structured the doc a bit better by making the procedures into headlines.

2017-07-11 11:11 UTC, mmoll approved these changes

2017-07-11 11:11 UTC, merged

2017-07-11 11:11 UTC, mmoll commented
merged, danke @bastilian!