Add foreman_openscap 0.8
theforeman/theforeman.org pull request #907
Opened 2017-07-10 11:51 UTC by ares

2017-07-10 11:51 UTC, ares commented
copy of 0.7, since 0.8 has been released already

2017-07-11 09:53 UTC, lzap requested changes
It's a good idea to make a copy in a separate commit to see the changes. Can you point on the paragraphs you have rewritten?

Would be a good idea to put images which are common into a common folder so we don't need to copy them every single release.

2017-07-11 09:53 UTC, lzap commented on plugins/foreman_openscap/0.8/index.md
> +version: 0.6.0
Is this the correct version (0.8)?

2017-07-11 09:53 UTC, lzap commented on plugins/foreman_openscap/0.8/index.md
> +</table>
Missing compatibility info.

2017-07-11 11:58 UTC, ares commented on plugins/foreman_openscap/0.8/index.md
> +version: 0.6.0
fixed, also fixed in 0.7 which I took for the copy

2017-07-11 11:58 UTC, ares commented on plugins/foreman_openscap/0.8/index.md
> +</table>
added

2017-07-11 11:59 UTC, ares commented
Thanks @lzap, I added fixes in second commit. First commit is 1:1 clone of 0.7. I'd prefer keeping images separate in case we need to modify them. Other plugins seems to do it the same way. We can always deduplicate if it takes too much space.

2017-07-12 11:36 UTC, lzap commented
Ok I am merging, haven't read all the text, don't know what changed.

2017-07-12 11:36 UTC, merged