Fixes #20335 - fix glossary link
theforeman/theforeman.org pull request #934
Opened 2017-08-18 18:42 UTC by johnpmitsch

2017-09-01 11:30 UTC, GregSutcliffe commented
@ehelms @jlsherrill ack? looks fine to me but I don't like touching Katello docs without confirmation :P

2017-10-11 09:48 UTC, sean797 requested changes
Looks right.. But we need to do the same thing for 2.4  -> 3.5 versions.

2017-10-17 14:01 UTC, johnpmitsch commented
@sean797 thanks, updated

2017-10-17 15:22 UTC, sean797 approved these changes

2017-10-17 15:45 UTC, merged