Adding hiera info for DHCP/DNS
theforeman/theforeman.org pull request #935
Opened 2017-08-22 10:37 UTC by lzap

@ekohl what is the DNS syntax again? I will add it.

2017-08-22 10:57 UTC, ekohl commented
For DNS you can use all parameters that https://github.com/theforeman/puppet-dns/blob/master/manifests/zone.pp has, similar to how you can use all parameters in https://github.com/theforeman/puppet-dhcp/blob/master/manifests/pool.pp for DHCP.

The ```reverse``` parameter is really badly named and should be ```add_a_record```. If you want a clean master zone example.com with just a ```NS``` record you'd use:
```yaml
dns::zones:
  example.com:
    reverse: true
```

2017-08-29 08:27 UTC, lzap commented
Could you please just give me two examples of typical DNS zone and reverse zone I can copy paste?

2017-08-29 10:53 UTC, ekohl commented
In the current version you can abuse the ```--foreman-proxy-dns-reverse``` option to create empty zones (including forwarding). So
```
foreman-installer --foreman-proxy-dns-reverse example.com --foreman-proxy-dns-reverse 1.168.192.in-addr.arpa
```

In the next version you should be able to use the ```dns::zones``` parameter as well through hiera. Note the following is untested because nightlies are broken.
```
dns::zones:
  example.com:
    # creates @ SOA $::fqdn root.example.com.
    # creates $::fqdn A $::ipaddress
  example.net:
    # creates @ SOA test.example.net. hostmaster.example.com.
    # creates test.example.net A 192.0.2.100
    soa: test.example.net
    soaip: 192.0.2.100
    contact: hostmaster.example.com.
  example.org:
    # creates @ SOA $::fqdn root.example.org.
    # does NOT create an A record
    reverse: true
  2.0.192.in-addr.arpa:
    # creates @ SOA $::fqdn hostmaster.example.com.
    reverse: true
    contact: hostmaster.example.com.
```

2017-08-30 10:34 UTC, lzap commented
So by current version you mean 1.15 and next version is 1.16/develop?

2017-08-30 10:43 UTC, lzap commented
Thanks rebased.

2017-08-30 11:00 UTC, ekohl commented
> So by current version you mean 1.15 and next version is 1.16/develop?

Correct.

2017-08-30 11:30 UTC, ekohl commented
Note that I'd like to test this once nightlies are up & running again.

2017-09-01 10:55 UTC, GregSutcliffe commented
@ekohl happy to merge once you've tested it :)

2017-09-01 11:00 UTC, ekohl commented
I also wonder if we should refer to some Foreman documentation in https://github.com/theforeman/foreman-installer/blob/develop/config/foreman.hiera/custom.yaml for some common examples.

2017-09-04 10:34 UTC, lzap commented
Honestly in config comment sections, I'd expect full and working examples so you can simply uncomment and edit them.

2017-09-04 17:59 UTC, ekohl commented
While I usually agree, there are so many options users could want that I don't know what examples we should include.

2017-09-05 13:26 UTC, lzap commented
Sure, what do you want me to do again? I am afraid I don't understand what do you want me to "refer to" and where exactly.

2017-09-21 12:27 UTC, ekohl commented
For some reason puppet-dns in the nightly builds does not contain the ```dns::zones``` parameter. I'll have to look into why it's stuck on the commit just before it was added.

2017-09-29 22:16 UTC, ekohl commented
Now that the nightlies are fixed I tested it and discovered a cyclic dependency when using the parameter. https://github.com/theforeman/puppet-dns/pull/97 should fix that including a test for it.

2017-10-02 18:06 UTC, ekohl commented
With that fixed I can now say I suggested some invalid YAML; I'd now suggest:
```yaml
dns::zones:
  # creates @ SOA $::fqdn root.example.com.
  # creates $::fqdn A $::ipaddress
  example.com: {}

  # creates @ SOA test.example.net. hostmaster.example.com.
  # creates test.example.net A 192.0.2.100
  example.net:
    soa: test.example.net
    soaip: 192.0.2.100
    contact: hostmaster.example.com.

  # creates @ SOA $::fqdn root.example.org.
  # does NOT create an A record
  example.org:
    reverse: true

  # creates @ SOA $::fqdn hostmaster.example.com.
  2.0.192.in-addr.arpa:
    reverse: true
    contact: hostmaster.example.com.
```

Other than that I think it's good to go.

2017-10-17 16:08 UTC, ekohl commented
Ping

2017-10-27 07:29 UTC, lzap commented
Sorry done.

2017-10-27 07:37 UTC, ekohl requested changes
Other than the one sentence I think it looks good.

2017-10-27 07:37 UTC, ekohl commented on plugins/katello/nightly/installation/index.md
> +Installer only supports one subnet and one DNS domain. Multiple entries can be
The installer only supports one subnet and one DNS domain via command line arguments.

2017-11-03 14:02 UTC, lzap commented
Done, finally thanks for huge help here!

2017-11-04 10:34 UTC, ekohl approved these changes
Anyone with merge permissions: please have a look :)

2017-11-05 10:39 UTC, ares commented
Thanks @lzap and @ekohl, merging

2017-11-05 10:39 UTC, merged