adding the ptable help to manual
theforeman/theforeman.org pull request #944
Opened 2017-09-12 15:21 UTC by shiramax

2017-09-30 18:10 UTC, mmoll commented
@shiramax please rebase

2017-10-16 07:11 UTC, shiramax commented
@mmoll Done.

2017-10-16 08:23 UTC, mmoll requested changes

2017-10-16 08:23 UTC, mmoll commented on _includes/manuals/1.16/4.4.4_prov_ptables.md
> +table will be found at /tmp/diskpart.cfg during the build process.
I'd enclose `#Dynamic` and `/tmp/diskpart.cfg` in that sentence with backticks, 👍 otherwise

2017-10-16 13:12 UTC, shiramax commented
@mmoll, 
Done, Please let me know if this is what you meant.

2017-10-16 14:15 UTC, mmoll approved these changes

2017-10-16 14:15 UTC, merged

2017-10-16 14:15 UTC, mmoll commented
this is fine, merged, thanks @shiramax!