Add documentation for configuring a HTTP proxy for requests
theforeman/theforeman.org pull request #948
Opened 2017-09-20 16:09 UTC by bastilian

Documentation for the new HTTP proxy settings: https://github.com/theforeman/foreman/pull/4640

2017-09-20 16:32 UTC, ares commented on _includes/manuals/1.16-develop/5.9_http_proxy.md
> +If Foreman is running behind a Firewall, that has HTTP port 80 and HTTPS port 443 blocked a HTTP proxy can be configured to allow requests to external compute resources, such as AWS EC2, Rackspace or
It does not have to be port 80/443, it applies to all communication with external systems, including foreman proxies. I don't date to suggest the sentence, but I think it should mention all external HTTP communication can be proxied and include few examples such as compute resource, foreman proxy, other endpoints coming from plugins e.g. docker registry.

2017-09-30 18:18 UTC, mmoll commented
@bastilian also, please rebase :)

2017-10-10 06:55 UTC, ares commented
@bastilian ping

2017-10-10 07:18 UTC, bastilian commented
@mmoll rebased.
@ares I changed the first sentence marginally. Any suggestion to make the documentation more readable and understandable is welcome! :)

2017-10-11 07:52 UTC, ares commented
Hm, the 1.16-develop does not seem to be included and we don't have 1.17 copy yet, I'm afraid we'll have to wait until we have 1.17 created. When I tried to generate pages, it failed to load the page since 1.16-develop is not searched. Otherwise good to go.

2017-11-14 06:04 UTC, dLobatog requested changes
@bastilian Please rebase so that 5.9_http_proxy is in manuals/1.16 instead of 1.16-develop, should be good to go after that. Thanks !

2017-11-15 08:17 UTC, bastilian commented
@dLobatog moved the docs into the 1.16 manuals.

2017-11-16 07:52 UTC, dLobatog approved these changes
Thanks @bastilian !

2017-11-16 07:53 UTC, merged