[WIP] - Manual for 1.17
theforeman/theforeman.org pull request #983
Opened 2017-12-07 13:03 UTC by xprazak2

2018-01-02 17:46 UTC, mmoll commented
please pull in the changes from GH-994

2018-01-03 10:28 UTC, xprazak2 commented
I pulled in changes from GH-994, thanks!

2018-01-11 12:34 UTC, lzap commented
Please pull https://github.com/theforeman/theforeman.org/pull/985 as well thanks.

2018-01-16 09:29 UTC, xprazak2 commented
I pulled in #985, thanks!

2018-01-16 14:27 UTC, xprazak2 commented
Added a list of features into release notes.

2018-01-17 10:06 UTC, xprazak2 commented on _includes/manuals/1.17/1.2_release_notes.md
> +* When seeding default roles, permission check and auditiong is ignored ([#21011](http://projects.theforeman.org/issues/21011))
@ares, does this seem ok to you?

2018-02-08 15:07 UTC, xprazak2 commented
This is no longer wip, ready for RC1

2018-02-08 15:14 UTC, ekohl requested changes

2018-02-08 15:14 UTC, ekohl commented on _includes/manuals/1.17/2.1_quickstart_installation.md
> +<div class="quickstart_os quickstart_os_debian8">
This block can be removed since Jessie was dropped

2018-02-08 15:14 UTC, ekohl commented on _includes/manuals/1.17/2.1_quickstart_installation.md
> +<div class="quickstart_os quickstart_os_debian8 quickstart_os_debian9 quickstart_os_ubuntu1604">
debian8 can also be removed here and below.

2018-02-08 15:14 UTC, ekohl commented on _includes/manuals/1.17/2_quickstart_guide.md
> +* Debian 8 (Jessie), i386/amd64/armhf/aarch64
This has been dropped

2018-02-08 15:14 UTC, ekohl commented on _includes/manuals/1.17/3.1.1_supported_platforms.md
> +* Fedora 24
We dropped F24 with 1.16 already.

2018-02-08 15:14 UTC, ekohl commented on _includes/manuals/1.17/3.1.1_supported_platforms.md
> +* Debian 8 (Jessie)
Was dropped

2018-02-08 15:14 UTC, ekohl commented on _includes/manuals/1.17/3.1.1_supported_platforms.md
> +* Ubuntu 14.04 (Trusty)
Was dropped

2018-02-08 16:21 UTC, ekohl requested changes

2018-02-08 16:21 UTC, ekohl commented on _includes/manuals/1.17/1.2_release_notes.md
> + * Support SSHFP dns records ([#20370](http://projects.theforeman.org/issues/20370))
This was closed, not resolved. https://github.com/theforeman/smart-proxy/pull/536 is still open

2018-02-08 16:21 UTC, ekohl commented on _includes/manuals/1.17/3.1.1_supported_platforms.md
> +The following operating systems are supported by the installer, have packages and are tested for deploying Foreman:
Debian Stretch is missing from this list.

2018-02-09 18:21 UTC, sean797 commented
Were probably want to updates some of the screenshots with the vertical nav?

2018-02-09 18:35 UTC, ekohl requested changes

2018-02-09 18:35 UTC, ekohl commented on _includes/manuals/1.16/4.1.1_authentication.md
> +#### Brute-force protection
Is this PR intended to change the 1.16 manual?

2018-02-09 18:35 UTC, ekohl commented on _includes/manuals/1.17/1.2_release_notes.md
> + * yum "latest" link maintained during releases ([#17019](http://projects.theforeman.org/issues/17019))
This has the release set to 1.16 now. It's also in the katello project and not Foreman but actually applied in the tooling around it.

2018-02-09 18:35 UTC, ekohl commented on _includes/manuals/1.17/1.2_release_notes.md
> + * Allow plugins webpack code to be used ([#20097](http://projects.theforeman.org/issues/20097))
Also has 1.16 set?

2018-02-09 18:35 UTC, ekohl commented on _includes/manuals/1.17/1.2_release_notes.md
> + * Update patternfly-react version to 0.18.2 ([#21990](http://projects.theforeman.org/issues/21990))
How much of this actually belongs here instead of the javascript stack section?

2018-02-09 18:35 UTC, ekohl commented on _includes/manuals/1.17/1.2_release_notes.md
> + * Add 3rd party js libraries in plugins ([#21180](http://projects.theforeman.org/issues/21180))
Does this belong in Plugins-Engines?

2018-02-09 18:35 UTC, ekohl commented on _includes/manuals/1.17/1.2_release_notes.md
> + * Remove custom eslint rules in favor of airbnb-base config ([#21624](http://projects.theforeman.org/issues/21624))
javascript stack?

2018-02-09 18:35 UTC, ekohl commented on _includes/manuals/1.17/1.2_release_notes.md
> + * Upgrade to latest recommended babel preset `env` ([#21462](http://projects.theforeman.org/issues/21462))
javascript stack?

2018-02-09 18:35 UTC, ekohl commented on _includes/manuals/1.17/1.2_release_notes.md
> + * Expose React components from plugins ([#20469](http://projects.theforeman.org/issues/20469))
Plugins-Engines?

2018-02-12 10:58 UTC, xprazak2 commented
I made changes to the release notes, added Stretch to the list of supported operating systems, moved the misplaced brute force protection from 1.16 to 1.17 docs, added screenshots with the new UI.

2018-02-12 13:50 UTC, ekohl approved these changes

2018-02-13 14:49 UTC, ares commented
Thanks @xprazak2 and @ekohl and all the rest.

2018-02-13 14:49 UTC, merged